#ifndef __MyProjectDialogNew__
#define __MyProjectDialogNew__

/**
@file
Subclass of DialogNew, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"

/** Implementing DialogNew */
class MyProjectDialogNew : public DialogNew
{
protected:
	// Handlers for DialogNew events.
	void OnCreate( wxCommandEvent& event );
	
public:
	/** Constructor */
	MyProjectDialogNew( wxWindow* parent );
};

#endif // __MyProjectDialogNew__
