#ifndef __MyProjectGUIFrame__
#define __MyProjectGUIFrame__

/**
@file
Subclass of GUIFrame, which is generated by wxFormBuilder.
*/

#include "GUIFrame.h"
#include "object.h"
//#include <math.h>
#include <wx/dcbuffer.h>
#include <wx/textdlg.h>
//#include <map>
//#include <list>
//#include <vector>
#include <iostream>
#include <fstream>

using namespace std;

/** Implementing GUIFrame */
class MyProjectGUIFrame : public GUIFrame
{
protected:
	// Handlers for GUIFrame events.
	void OnClose( wxCloseEvent& event );
	void OnTreeCtrlItemActivated( wxTreeEvent& event );
	void OnTextEnergy( wxCommandEvent& event );
	void OnTextAttack( wxCommandEvent& event );
	void OnTextLifetime( wxCommandEvent& event );
	void OnTextInitVelocity( wxCommandEvent& event );
	void OnCheckBoxCollDetection( wxCommandEvent& event );
	void OnChoiceInitialState( wxCommandEvent& event );
	void OnTextInitialAnimFrame( wxCommandEvent& event );
	void OnTextAnimLifetime( wxCommandEvent& event );
	void OnCheckBoxAnimated( wxCommandEvent& event );
	void OnTextGfxFile( wxCommandEvent& event );
	void OnScrWindowClick( wxMouseEvent& event );
	void OnScrWindowMotion( wxMouseEvent& event );
	void OnScrWindowPaint( wxPaintEvent& event );
	void OnScrWindowRClick( wxMouseEvent& event );
	void OnMenuItemNew( wxCommandEvent& event );
	void OnMenuItemOpen( wxCommandEvent& event );
	void OnMenuItemSave( wxCommandEvent& event );
	void OnMenuItemSaveAs( wxCommandEvent& event );
	void OnMenuItemCopy( wxCommandEvent& event );
	void OnMenuItemPaste( wxCommandEvent& event );
	void OnMenuItemCut( wxCommandEvent& event );
	void OnMenuItemSelectAll( wxCommandEvent& event );
	void OnMenuItemCancelSelection( wxCommandEvent& event );
	void OnMenuItemDeleteSelected( wxCommandEvent& event );
	void OnMenuItemEditMode( wxCommandEvent& event );
	void OnMenuItemSelectionMode( wxCommandEvent& event );
	void OnMenuItemDeletionMode( wxCommandEvent& event );
	void OnMenuItemMagnetize( wxCommandEvent& event );
	void OnMenuItemShowObjects( wxCommandEvent& event );
	void OnMenuItemShowTiles( wxCommandEvent& event );
	void OnMenuItemAbout( wxCommandEvent& event );
    void OnMenuItemClone ( wxCommandEvent& event );
    void OnMenuItemShowGrid( wxCommandEvent& event);
    void OnMenuItemDockOnGrid( wxCommandEvent& event);
    void OnMenuItemConfigGrid( wxCommandEvent& event);
    void OnSpinCtrlXCoord ( wxCommandEvent& event);
    void OnSpinCtrlYCoord ( wxCommandEvent& event);
    void OnMenuItemFrameMode( wxCommandEvent& event);

public:
	/** Constructor */
	MyProjectGUIFrame( wxWindow* parent );
	/** helper functions*/
	int FillPropertyWindow(EDOBJEKT object);
	void RefreshScreen(void);
	void PushFromPasteBuffer(void);
	void CreateNewLevel(void);

};

// global function
void SetLevelSizes(int x, int y);

enum modes {MODE_EDIT, MODE_SELECTION, MODE_DELETE, MODE_FRAME};

#endif // __MyProjectGUIFrame__
