// Fragen Editor 1.1

function get_questions() {

  load_question(['a) Die Zusammensetzung der inneren und äusseren Lipidschicht ist unterschiedlich,<br><br>weil<br><br>b) die Lipide die Lipidschicht leicht wechseln können.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'C', 1, 'none' ]) ;
  load_question(['a) Transmembranproteine sind über einen GPI-Anker mit der Lipidschicht verbunden,<br><br>weil<br><br>b) Transmembranproteine nur mit Detergenzien aus der Lipiddoppelschicht herausgelöst werden können.', ['a und b richtig; b als Begründung von a richtig', ' GPI-verankerte Proteine durchdringen die Membran in der Regel nicht'], ['a und b richtig; b als Begründung von a falsch', ' GPI-verankerte Proteine durchdringen die Membran in der Regel nicht'], ['a richtig, b falsch', ' GPI-verankerte Proteine durchdringen die Membran in der Regel nicht'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Das Innere von Transmembranproteinen ist viel hydrophober als das Innere von wasserlöslichen, globulären Proteinen,<br><br>weil<br><br>b) sie die Lipiddoppelschicht durchdringen.', ['a und b richtig; b als Begründung von a richtig', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a und b richtig; b als Begründung von a falsch', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a richtig, b falsch', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a falsch, b richtig', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a falsch, b falsch', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], 'D', 2, 'none' ]) ;
  load_question(['Welche Geschwindigkeit trifft am ehesten zu für die Drehung von Lipiden in der Lipiddoppelschicht bei 37 °C?', ['10<sup>2</sup> pro Sekunde', ' '], ['10<sup>5</sup> pro Sekunde', ' '], ['10<sup>9</sup> pro Sekunde', ' '], ['10<sup>12</sup> pro Sekunde', ' '], ['10<sup>16</sup> pro Sekunde', ' '], 'C', 0, 'none' ]) ;
  load_question(['Wieviele Aminosäuren lang muss eine alpha-Helix sein, damit sie eine 30 Angström dicke Lipiddoppelschicht durchdringt?', ['5', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['10', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['15', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['20', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['25', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], 'D', 0, 'none' ]) ;
  load_question(['FRAP-Experimente (fluorescence recovery after photobleaching) zeigen, dass', ['verschiedene Zellen miteinander fusionieren können', ' '], ['Proteine asymmetrisch angeordnet sind', ' '], ['Lipide nicht schnell zwischen der inneren und äusseren Schicht austauschen', ' '], ['Proteine in der Lipiddoppelschicht lateral beweglich sind', ' '], ['Proteine die Membran durchdringen', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welches Lipid ist ein typischer Bestandteil von biologischen Membranen?<br><br>1. Cholesterin<br>2. Phosphatidylcholin<br>3. Cerebrosid<br>4. Cholsäure', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Cholsäure ist amphiphil und kann als Detergens Membranen auflösen!'], ['1, 2, 3 und 4 treffen zu', ' Cholsäure ist amphiphil und kann als Detergens Membranen auflösen!'], 'A', 1, 'none' ]) ;
  load_question(['Welches Lipid kommt in biologischen Membranen üblicherweise nicht vor?', ['1, 2, und 3 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['1 und 3 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['2 und 4 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['4 trifft zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['1, 2, 3 und 4 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], 'C', 1, 'testbilder/040103.gif' ]) ;
  load_question(['Wie können Membranproteine die Lipiddoppelschicht durchqueren?<br><br>1. als <img src="testbilder/alpha.gif">-Helix<br>2. als gestreckte Peptidkette<br>3. als <img src="testbilder/beta.gif">-Faltblatt<br>4. über einen GPI-Anker', ['1, 2, und 3 treffen zu', ''], ['1 und 3 treffen zu', ''], ['2 und 4 treffen zu', 'Proteine mit einem GPI-Anker sitzen meistens aussen an der Membran'], ['4 trifft zu', 'Proteine mit einem GPI-Anker sitzen meistens aussen an der Membran'], ['1, 2, 3 und 4 treffen zu', 'Proteine mit einem GPI-Anker sitzen meistens aussen an der Membran'], 'B', 1, 'none' ]) ;
  load_question(['Erythrocyten werden mit einem für Zucker spezifischen Reagens behandelt.<br>Welche Proteine werden dadurch chemisch modifiziert?<br><br>1. Transmembranproteine<br>2. Proteine auf der Innenseite der Membran<br>3. Proteine auf der Aussenseite der Membran<br>4. Alle Membranproteine', ['1, 2, und 3 treffen zu', 'Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['1 und 3 treffen zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['2 und 4 treffen zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['4 trifft zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['1, 2, 3 und 4 treffen zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage über Cholesterin trifft zu?<br><br>1. Es ist ein häufiger Membranbestandteil<br>2. Es schränkt die Beweglichkeit der Membranlipide ein<br>3. Es ist in die innere und äussere Lipidschicht eingelagert<br>4. Es erniedrigt die Durchlässligkeit der Lipidschicht für Wasser', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welche Antwort zur gezeigten posttranslationellen Modifikation des N-Terms eines Proteins ist richtig? (farbige Sechsecke symbolisieren Zuckermoleküle)', ['Durch die Modifikation wird das Protein zu einem wertvolleren Nahrungsmittel', ' '], ['Durch die Modifikation wird das Protein besser wasserlöslich', ' '], ['Durch die Modifikation wird das Protein vom Immunsystem besser als ein fremdes Molekül erkannt', ' '], ['Durch die Modifikation wird das Protein in der Lipiddoppelschicht einer Membran leichter beweglich', ' '], ['Durch die Modifikation wird das Protein in der Lipiddoppelschicht einer Membran verankert', ' '], 'E', 0, 'testbilder/GPI-anker-stryer.gif' ]) ;
  load_question([' Welche Aussage über die gezeigte Fluiditätskurve einer Lipiddoppelschicht ist richtig? <br><br>1. Ungesättigte Fettsäuren erhöhen Tm<br>2. Cis-Doppelbindungen erniedrigen Tm<br>3. Cholesterin hat keinen Einfluss auf Tm<br>4. Tm der Lipiddoppelschicht eines Erythrozyten ist tiefer als 37 °C ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'C', 1, 'testbilder/fluidity2-stryer.gif' ]) ;
  load_question(['Welche Aussage über Porin ist richtig? <br><br>1. Es ist ein Transmembranprotein<br>2. Es besteht aus polaren und apolaren Aminosäuren<br>3. In den Strängen des beta-Faltblatts alternieren polare und apolare Aminosäuren<br>4. Die polaren Aminosäuren sind vorwiegend gegen das Innere des Porinmoleküls gerichtet ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'E', 1, 'testbilder/voet1128a.jpg' ]) ;
  
}