// Fragen Editor 1.1
   
 

 

function get_questions() {

  load_question(['Zuordnung:<br><br>A Aufbau von Biomolekülen<br>B Abbau von Biomolekülen<br>C Reihenfolge der Enzymreaktionen im Fliessgleichgewicht<br>D Aktivierungsenergie<br>E NAD<sup>+</sup>', ['Katabolismus', ' '], ['Anabolismus', ' '], ['Stoffwechselweg', ' '], ['Übergangszustand', ' '], ['Oxidoreduktase', ' '], ['B', 'A', 'C', 'D', 'E'], 3, 'none' ]) ;
  load_question(['Bei einer Enzymreaktion ist K<sub>m</sub> für Substrat A 1 mM und für Substrat B 10 mM. Welche Aussage ist richtig?', ['Es braucht mehr A als B um V<sub>max</sub> zu erreichen', ' '], ['Es braucht weniger A als B um V<sub>max</sub> zu erreichen', ' '], ['Es braucht 10mal mehr B, um V<sub>max</sub> zu erreichen', ' '], ['Es braucht 10mal mehr A, um V<sub>max</sub> zu erreichen', ' '], ['Keine der obigen Aussagen ist richtig', ' '], 'B', 0, 'none' ]) ;
  load_question(['In einem Enzymassay misst man eine Absorptionsänderung von 0.3 min<sup>-1</sup> cm<sup>-1</sup>. Exktinktionskoeffizient = 6 mM<sup>-1</sup> cm<sup>-1</sup>, Proteinkonzentration = 400 mg<sup></sup> L<sup>-1</sup>. Welches Wertepaar für die Enzymaktivität (U/L) und die spezifische Enzymaktivität (U/mg) ist richtig?', ['5 U/L und 1.25 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['50 U/L und 12.5 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['50 U/L und 0.125 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['50 U/L und 1.25 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['5 U/L und 12.5 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], 'C', 0, 'none' ]) ;
  load_question(['Welche Definition der Enzymaktivität U ist richtig?', ['1 U = 1 µmol Substrat/min', ' '], ['1 U = 1 millimol Substrat/min', ' '], ['1 U = 1 µmol Substrat/cm', ' '], ['1 U = 1 µmol Substrat/min mg', ' '], ['1 U = 1 millimol Substrat/mg', ' '], 'A', 0, 'none' ]) ;
  load_question(['Eine Enzmylösung hat eine Aktivität von 1 U/L. Die Konzentration des reinen Enzyms in der Lösung beträgt 0.02 Mikromol/L. Wie gross ist die molekulare Aktivität des Enzyms?', ['0.1 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['1 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['5 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['50 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['100 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], 'D', 0, 'none' ]) ;
  load_question(['Welche Informationen sind unerlässlich, um einen Stoffwchselweg zu beschreiben?', ['E.C. Nummern der beteiligten Enzyme', ' '], ['Reihenfolge der einzelnen Reaktionsschritte', ' '], ['enzymatische Mechanismen aller Reaktionsschritte', ' '], ['Regulation aller Reaktionsschritte', ' '], ['optimale pH-Werte aller Reaktionsschritte', ' '], 'B', 0, 'none' ]) ;
  load_question(['Welche Differenz der freien Enthalpie wird vom Enzym erniedrigt?', ['<img src="testbilder/delta.gif">G zwischen S und P', ' '], ['<img src="testbilder/delta.gif">G zwischen E + S und ES', ' '], ['<img src="testbilder/delta.gif">G zwischen E + S und ES<sup>#</sup>', ' '], ['<img src="testbilder/delta.gif">G zwischen E + P und EP', ' '], ['<img src="testbilder/delta.gif">G zwischen E und E<sup>#</sup>', ' '], 'C', 0, 'none' ]) ;
  load_question(['Wie nennt man das Enzym, von dem alle Nichtproteinteile entfernt worden sind?', ['Holoenzym', ' '], ['Zymogen', ' '], ['Proenzym', ' '], ['Coenzym', ' '], ['Apoenzym', ' '], 'E', 0, 'none' ]) ;
  load_question(['Welche Aussage ist <span class="fett">falsch</span>?', ['K<sub>m</sub> = [S] bei V<sub>max</sub>/2', ' '], ['V<sub>max</sub> = v bei [S] >> K<sub>m</sub>', ' '], ['Anfangsgeschwindigkeit = v bei [S] << K<sub>m</sub>', ' '], ['MM-Gleichung gilt nur für Anfangsgeschwindigkeiten', ' '], ['MM-Gleichung gilt nur für [ES] = konstant', ' '], 'C', 0, 'none' ]) ;
  load_question(['Welches ist der Wert des Schnittpunkts mit der X-Achse in einer Lineweaver-Burk Darstellung, welche mit der nebenstehenden Gleichung beschrieben wird?', ['1/V<sub>max</sub>', ' '], ['-1/V<sub>max</sub>', ' '], ['1/K<sub>m</sub>', ' '], ['-1/K<sub>m</sub>', ' '], ['K<sub>m</sub>/V<sub>max</sub>', ' '], 'D', 0, 'testbilder/gle0710.gif' ]) ;
  load_question(['Wie gross ist v einer Enzymreaktion mit MM-Mechanismus, wenn [S] = 5K<sub>m</sub>?', ['5/4 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['4/5 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['6/4 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['4/6 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['5/6 V<sub>max</sub>', ' '], 'E', 0, 'none' ]) ;
  load_question(['Zu welcher Grösse ist die Geschwindigkeit einer Enzymreaktion linear proportional?', ['-<img src="testbilder/delta.gif">G/RT', ' '], ['<img src="testbilder/delta.gif">G<sup>#</sup>/RT', ' '], ['exp(<img src="testbilder/delta.gif">G<sup>#</sup>/RT)', ' '], ['exp(-<img src="testbilder/delta.gif">G<sup>#</sup>/RT)', ' '], ['ln(<img src="testbilder/delta.gif">G<sup>#</sup>/RT)', ' '], 'D', 0, 'none' ]) ;
  load_question(['Eine Enzymreaktion braucht ATP als Substrat. AMP ist ein kompetitiver Inhibitoren der Reaktion, Adenosin hemmt die Reaktion nicht. Welche Folgerung kann man aus dieser Beobachtung schliessen?', ['Adenosin ist zu gross, um an die aktive Stelle zu binden', ' '], ['Adenosin bindet ausserhalb der aktiven Stelle', ' '], ['Der Ribosering ist für die Hemmung nötig', ' '], ['Die Phosphatgruppe ist für die Hemmung nötig', ' '], ['Adenin ist für die Hemmung nötig', ' '], 'D', 0, 'none' ]) ;
  load_question(['Welche Kurve beschriebt eine Reaktion mit positiver Kooperativität?', ['grün', ' '], ['schwarz', ' '], ['gelb', ' '], ['rot', ' '], ['blau', ' '], 'D', 0, 'testbilder/070117.gif' ]) ;
  load_question(['Zu welcher Klasse gehört das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'E', 0, 'testbilder/070108.gif' ]) ;
  load_question(['Zu welcher Klasse gehört das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'D', 0, 'testbilder/070109.gif' ]) ;
  load_question(['Zu welcher Klasse gehört das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'A', 0, 'testbilder/070110.gif' ]) ;
  load_question(['Zu welcher Klasse gehört das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Ligasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'C', 0, 'testbilder/070112.gif' ]) ;
  load_question(['Zu welcher Klasse gehört das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'B', 0, 'testbilder/070113.gif' ]) ;
  load_question(['Welche Funktionen üben Coenzyme und prosthetische Gruppen aus?<br><br>1. Wasserstoffübertragung bei Redoxreaktionen<br>2. Elektronenübertragung bei Redoxreaktionen<br>3. Decarboxylierungs- und Carboxylierungsreaktionen<br>4. Übertragung von Alkyl- und Acylgruppen', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welches Coenzym ist an Redoxreaktionen beteiligt?<br><br>1. Nicotinamidadenindinucleotid<br>2. Pyridoxalphosphat<br>3. Flavinadenindinucleotid<br>4. Coenzym A', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Alkoholdehydrogenase (ADH) kommt sowohl in der menschlichen Leber als auch in der Hefe vor. Welche Aussage trifft zu?<br><br>1. In der Leber ist die bevorzugte Reaktionsrichtung Ethylalkohol <img src="testbilder/pfeilrechts.gif"> Acetaldehyd<br>2. Die ADH der Leber beschleunigt nur die Reaktion Ethylalkohol <img src="testbilder/pfeilrechts.gif"> Acetaldehyd<br>3. In der Hefe ist die bevorzugte Reaktionsrichtung Acetaldehyd <img src="testbilder/pfeilrechts.gif"> Ethylalkohol<br>4. Die ADH der Hefe beschleunigt nur die Reaktion Acetaldehyd <img src="testbilder/pfeilrechts.gif"> Ethylalkohol</p>', ['1, 2, und 3 treffen zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['4 trifft zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['1, 2, 3 und 4 treffen zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage über Isoenzyme ist richtig?<br><br>1. Sie können fast gleiche pI aufweisen<br>2. Sie können sehr ähnliche Aminosäurensequenzen haben<br>3. Sie können fast dasselbe Molekulargewicht haben<br>4. Sie können im gleichen Gewebe vorkommen', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welche Aussage über Isoenzyme ist richtig?<br><br>1. Sie können sehr unterschiedliche Aminosäurensequenzen haben<br>2. Sie können sehr unterschiedliche Molekulargewichte haben<br>3. Sie können aus mehreren Untereinheiten bestehen<br>4. Sie können in verschiedenen Spezies vorkommen', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Isoenzyme kommen definitionsgemäss immer in derselben Spezies vor'], ['1, 2, 3 und 4 treffen zu', ' Isoenzyme kommen definitionsgemäss immer in derselben Spezies vor'], 'A', 1, 'none' ]) ;
  load_question(['Die Y-Achse zeigt die die Geschwindigkeit v einer Enzymreaktion vom MM-Typ.<br> Welche Zuordnungen der X-Achsen sind richtig?<br><br>1. Achse 1 = [Substrat], Achse 2 = [Enzym], Achse 3 = pH<br>2. Achse 1 = [Coenzym], Achse 2 = [Enzym], Achse 3 = Temperatur<br>3. Achse 1 = [Enzym], Achse 2 = [Substrat], Achse 3 = pH<br>4. Achse 1 = [Substrat], Achse 2 = [Enzym], Achse 3 = Temperatur', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'testbilder/070114.gif' ]) ;
  load_question(['Die Seitenkette welcher Aminosäure kann an einer Säure-Basen Katalyse teilnehmen?<br><br>1. His<br>2. Leu<br>3. Asp<br>4. Ala', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage zum Übergangszustand einer Enzymreaktion ist richtig?<br><br>1. er ist sehr kurzlebig<br>2. seine Konzentration ist verschwindend klein<br>3. er ist verschieden vom Übergangszustand der nichtkatalysierten Reaktion<br>4. er hat eine höhere freie Energie als S und P', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welche Faktoren beeinflussen V<sub>max</sub> einer Enzymreaktion?<br><br>1. pH<br>2. Temperatur<br>3. Enzymkonzentration<br>4. Substratkonzentration<br>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Vmax ist erreicht, wenn [S] unendlich gross, demzufolge kann [S] Vmax nicht beeinflussen '], ['1, 2, 3 und 4 treffen zu', ' Vmax ist erreicht, wenn [S] unendlich gross, demzufolge kann [S] Vmax nicht beeinflussen '], 'A', 1, 'none' ]) ;
  load_question(['Welche Faktoren beeinflussen K<sub>m</sub> einer Enzymreaktion?<br><br>1. pH<br>2. Substratkonzentration<br>3. Temperatur<br>4. Enzymkonzentration<br>', ['1, 2, und 3 treffen zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['4 trifft zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['1, 2, 3 und 4 treffen zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], 'B', 1, 'none' ]) ;
  load_question(['Die Summe welcher Konzentrationen bleibt im Verlauf einer Enzymreaktion, die bis zur Einstellung des thermodynamischen Gleichgewichts abläuft, konstant?<br><br>1. [E] + [ES]<br>2. [E] + [P]<br>3. [EP] + [P]<br>4. [S] + [P]', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welche Annahme liegt dem Michaelis-Menten-Mechanismus zugrunde?<br><br>1. v = Anfangsgeschwindigkeit<br>2. d[ES]/dt = 0<br>3. [S] >> [E]<br>4. T = 37 °C', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Welche Aussage über ein kooperativ reguliertes Enzyms ist richtig?<br><br>1. v = f([S]) hat stets die Form einer Hyperbel<br>2. positive Kooperativität verstärkt die Bindung des Substrats<br>3. negative Kooperativität verhindert die Bindung des Substrats<br>4. das Enzym hat meist mehrere Untereinheiten </p>', ['1, 2, und 3 treffen zu', ' negative Kooperativität zeigt keine Hyperbel und bewirkt nur, dass S schlechter bindet'], ['1 und 3 treffen zu', ' negative Kooperativität zeigt keine Hyperbel und bewirkt nur, dass S schlechter bindet'], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' negative Kooperativität zeigt keine Hyperbel und bewirkt nur, dass S schlechter bindet'], 'C', 1, 'none' ]) ;
  load_question(['Welche Aussage über allosterisch regulierte Enzyme ist richtig?<br><br>1. sie besitzen mindestens 2 Untereinheiten<br>2. ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat<br>3. ein heterotroper allosterischer Inhibitor bindet an einem anderen Ort als das Substrat<br>4. ein homotroper allosterischer Inhibitor verdrängt das Substrat aus der Bindungsstelle', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat, er bindet aber an eine regulatorische Stelle und nicht an die Substratbindungsstelle'], ['1, 2, 3 und 4 treffen zu', ' ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat, er bindet aber an eine regulatorische Stelle und nicht an die Substratbindungsstelle'], 'A', 1, 'none' ]) ;
  load_question(['Welche Aussage über allosterisch regulierte Enzyme ist richtig?<br><br>1. sie kommen in zwei unterschiedlichen Konformationen, T und S, vor<br>2. ein allosterischer Regulator ändert das Verhältnis T/S<br>3. T- und S-Form binden das Substrat unterschiedlich stark<br>4. Rückkopplungshemmung benötigt mindestens ein allosterisch reguliertes Enzym', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['ATP hemmt die Reaktion Glucose + ATP <img src="testbilder/pfeilrechts.gif"> Glucose-6-Phosphat + ADP.<br>Welche Aussage ist richtig?<br><br>1. ATP ist ein homotroper allosterischer Inhibitor<br>2. ATP ist ein heterotroper allosterischer Inhibitor<br>3. ATP ist ein Substrat<br>4. ATP ist ein kompetitiver Inhibitor', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage über die Zymogenaktivierung ist <span class="fett">falsch</span>?<br>1. sie kommt nur bei Enzymen im Magendarmtrakt vor<br>2. sie verhindert die vorzeitige Aktivierung des Enzyms<br>3. sie dient der Inaktivierung eines Enzyms<br>4. sie ist reguliert', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['a) Katabole und anabole Stoffwechselwege sind in der Regel identisch,<br><br>weil<br><br>b) sie von denselben Enzymen katalysiert werden.', ['a und b richtig; b als Begründung von a richtig', ' wenn es so wäre, könnten Auf- und Abbau nicht reguliert werden'], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'E', 2, 'none' ]) ;
  load_question(['a) Erkenntnisse über die Katalyse von chemischen Reaktionen sind auf Enzymreaktionen nicht anwendbar,<br><br>weil<br><br>b) chemische Katalysatoren keine Proteine sind.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Die Aktivität eines Enzyms kann durch Phosphorylierung von Ser kontrolliert werden,<br><br>weil<br><br>b) Ser an der aktiven Stelle von Enzymen vorkommen kann.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) Enzyme zeigen ein pH-Optimum der Aktivität,<br><br>weil<br><br>b) die Enzymaktivität vom Ladungszustand des Substrats und der aktiven Stelle abhängt.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'A', 2, 'none' ]) ;
  load_question(['a) Phosphorylierung eines Enzyms kann die Aktivität erhöhen oder erniedrigen,<br><br>weil<br><br>b) die Phosphatgruppe durch Phosphatase wieder abgespalten werden kann.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) ATP ist ein Feedback-Inhibitor der Glykolyse,<br><br>weil<br><br>b) ATP alle Schritte der Gykolyse allosterisch hemmt.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'C', 2, 'none' ]) ;
  
}