// Fragen Editor 1.1
   
 

 

function get_questions() {

  load_question(['Welche Verbindung kommt in Proteoglykanen <span class="fett">nicht</span> vor?', ['Heparin', ' '], ['Chondroitinsulfat', ' '], ['Hyalurons&auml;ure', ' '], ['Core Peptid', ' '], ['Glykolipid', ' '], 'E', 0, 'none' ]) ;
  load_question(['Mit der Seitenkette welcher Aminos&auml;ure sind Zucker kovalent verbunden?', ['Asp', ' '], ['Asn', ' '], ['Glu', ' '], ['Gln', ' '], ['Cys', ' '], 'B', 0, 'none' ]) ;
  load_question(['Wie heisst dieses Heteroglykan?', ['Dextran', ' '], ['Inulin', ' '], ['Hyalurons&auml;ure', ' '], ['Polysaccharose', ' '], ['Chondroitinsulfat', ' '], 'C', 0, 'testbilder/050101.gif' ]) ;
  load_question(['Wie gross ist die Energiereserve, die der Mensch in Form von Blutglucose besitzt; gemessen in Prozent des Tagesbedarfs von 10’000 kJ? (Blutvolumen = 5 l, [Glucose] = 5 mM, Energiegehalt = 20 kJ/g Glucose)', ['1%', ' '], ['5%', ' '], ['10%', ' '], ['15%', ' '], ['25%', ' '], 'A', 0, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber den Zuckerteil von Glykoproteinen ist <span class="fett">falsch</span>?', ['er beeinflusst die Konformation des Proteinteils', ' '], ['er ist kovalent an das Protein gebunden', ' '], ['er ist bei allen Glykoproteinen sehr &auml;hnlich', ' '], ['er enth&auml;lt Zuckerderivate', ' '], ['er wird posttranslationell gebildet', ' '], 'C', 0, 'none' ]) ;
  load_question(['Welches der folgenden Polysaccharide ist <span class="fett">kein</span> Polymer der Glucose?', ['Amylopektin', ' '], ['Amylose', ' '], ['Glycogen', ' '], ['Murein', ' '], ['Glycogen', ' '], 'D', 0, 'none' ]) ;
  load_question(['Wie heisst dieses Homoglykan?', ['St&auml;rke', ' Stärke enthält alpha-glykosidisch verknüpfte Glucosereste'], ['Glykogen', ' Glykogen enthält alpha-glykosidisch verknüpfte Glucosereste'], ['Saccharose', ' Inulin ist Polyfructose'], ['Lactose', ' Chitin ist ein Polymer von N-Acetylglucosamin'], ['Cellulose', ' '], 'E', 0, 'testbilder/050102.gif' ]) ;
  load_question(['Welche Aussage &uuml;ber Glykoproteine trifft zu?', ['Zucker und Protein sind &uuml;ber elektrostatische Kr&auml;fte aneinander gebunden', ' '], ['sie enthalten viele repetitive Disaccharideinheiten', ' '], ['sie binden viel Wasser', ' '], ['sie kommen vorwiegend extrazellul&auml;r vor', ' '], ['', ' '], ['0', '0', '0', '1'], 6, 'none' ]) ;
  load_question(['Welche Aussage ist richtig?', ['Der Zuckeranteil ist bei Glykoproteinen geringer als bei Proteoglykanen', ' '], ['Amylose ist ein unverzweigtes Homoglykan', ' '], ['Inulin passiert die Glomerulusmembran ungehindert', ' '], ['Cellulose ist eine wichtige Energiequelle bei vegetarischer Ern&auml;hrung', ' '], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche der folgenden Verbindungen ist ein Polysaccharid?', ['Hyalurons&auml;ure', ' '], ['<img src="testbilder/beta.gif">-Carotin', ' '], ['Heparin', ' '], ['Keratin', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['a) Der Energiegehalt von Salat ist f&uuml;r den Menschen niedrig,<br><br>weil<br><br>b) der Mensch keine <img src="testbilder/alpha.gif">-Glucosidase besitzt.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a richtig, b falsch', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a falsch, b richtig', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a falsch, b falsch', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], 'C', 2, 'none' ]) ;
  load_question(['a) Penicillin behindert den Aufbau von Peptidoglykanen in der Bakterienzellwand,<br><br>weil<br><br>b) es ein Enzym hemmt, das die Quervernetzung der Peptide katalysiert.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'A', 2, 'none' ]) ;
  load_question(['a) Lysozym hemmt die Bildung der Bakterienwand,<br><br>weil<br><br>b) es eine Peptidbindung in Murein spaltet.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a richtig, b falsch', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a falsch, b richtig', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a falsch, b falsch', ' Lysozym spaltet glykosidische Bindungen im Murein '], 'E', 2, 'none' ]) ;
  load_question(['Zuordnung:<br><br>A Knorpel<br>B Cellulose<br>C Amylose<br>D Bakterienzellwand<br>E Milchzucker', ['Lactose', ' '], ['<img src="testbilder/alpha.gif">-1,4-glykosidische Bindung', ' '], ['<img src="testbilder/beta.gif">-1,4-glykosidische Bindung', ' '], ['Proteoglykane', ' '], ['Peptidoglykane', ' '], ['E', 'C', 'B', 'A', 'D'], 3, 'none' ]) ;
  load_question(['Zuordnung:<br><br>A Heteroglykan<br>B Glykoprotein<br>C Peptidoglykan<br>D Glykolipid<br>E Core Protein', ['Membranprotein', ' '], ['Hyalurons&auml;ure', ' '], ['Hauptbestandteil der Bakterienzellwand', ' '], ['Membranlipid', ' '], ['Proteoglykan', ' '], ['B', 'A', 'C', 'D', 'E'], 3, 'none' ]) ;
  load_question(['Zuordnung:', ['N-glykosidische Bindung', ' '], ['<img src="testbilder/beta.gif">-1,3-glykosidische Bindung', ' '], ['<img src="testbilder/alpha.gif">-1,4-glykosidische Bindung', ' '], ['Peptidbindung', ' '], ['Amidbindung', ' '], ['D', 'A', 'B', 'E', 'C'], 3, 'testbilder/050103.gif' ]) ;
  load_question(['Welche Aussage &uuml;ber die mit einem Buchstaben bezeichnete Gruppe ist falsch?', ['alpha-1,6-glykosidische Bindung', ' '], ['alpha-1,4-glykosidische Bindung', ' '], ['nicht-reduzierendes Ende', ' '], ['reduzierendes Ende', ' '], ['C6-Atom von Glucose', ' '], 'D', 0, 'testbilder/glykogen-stryer.gif' ]) ;
  load_question(['Wo kommt das gezeigte Molek&uuml;l vor?', ['in St&auml;rke', ' '], ['in sauren Mucopolysacchariden', ' '], ['in Glykoproteinen', ' '], ['in Glycosaminoglykanen ', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'testbilder/heparin.jpg' ]) ;
  load_question(['Welche Aussage &uuml;ber das gezeigte Molek&uuml;l ist richtig?', ['Es ist ein Proteoglykan', ' '], ['Es ist Glykolipid', ' '], ['Es ist ein Glykosaminoglykan ', ' '], ['Es ist ein saures Mucopolysaccharid', ' '], ['Keine der obigen Antworten ist richtig', ' '], 'B', 0, 'testbilder/abb0406.gif' ]) ;
  
}