// Fragen Editor 1.1
   
 

 

function get_questions() {

  load_question(['Zuordnung:<br><br>A Aufbau von Biomolek&uuml;len<br>B Abbau von Biomolek&uuml;len<br>C Reihenfolge der Enzymreaktionen im Fliessgleichgewicht<br>D Aktivierungsenergie<br>E NAD<sup>+</sup>', ['Katabolismus', ' '], ['Anabolismus', ' '], ['Stoffwechselweg', ' '], ['&Uuml;bergangszustand', ' '], ['Oxidoreduktase', ' '], ['B', 'A', 'C', 'D', 'E'], 3, 'none' ]) ;
  load_question(['Bei einer Enzymreaktion ist K<sub>m</sub> f&uuml;r Substrat A 1 mM und f&uuml;r Substrat B 10 mM. Welche Aussage ist richtig?', ['Es braucht mehr A als B um V<sub>max</sub> zu erreichen', ' '], ['Es braucht weniger A als B um V<sub>max</sub> zu erreichen', ' '], ['Es braucht 10mal mehr B, um V<sub>max</sub> zu erreichen', ' '], ['Es braucht 10mal mehr A, um V<sub>max</sub> zu erreichen', ' '], ['Keine der obigen Aussagen ist richtig', ' '], 'B', 0, 'none' ]) ;
  load_question(['In einem Enzymassay misst man eine Absorptions&auml;nderung von 0.3 min<sup>-1</sup> cm<sup>-1</sup>. Exktinktionskoeffizient = 6 mM<sup>-1</sup> cm<sup>-1</sup>, Proteinkonzentration = 400 mg<sup></sup> L<sup>-1</sup>. Welches Wertepaar f&uuml;r die Enzymaktivit&auml;t (U/L) und die spezifische Enzymaktivit&auml;t (U/mg) ist richtig?', ['5 U/L und 1.25 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['50 U/L und 12.5 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['50 U/L und 0.125 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['50 U/L und 1.25 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], ['5 U/L und 12.5 U/mg', ' U/L = 0.3/6 = 0.05 mmol/L×min = 50 umol/L×min = 50 U/L, 50/400 = 0.125 U/mg'], 'C', 0, 'none' ]) ;
  load_question(['Welche Definition der Enzymaktivit&auml;t U ist richtig?', ['1 U = 1 µmol Substrat/min', ' '], ['1 U = 1 millimol Substrat/min', ' '], ['1 U = 1 µmol Substrat/cm', ' '], ['1 U = 1 µmol Substrat/min mg', ' '], ['1 U = 1 millimol Substrat/mg', ' '], 'A', 0, 'none' ]) ;
  load_question(['Eine Enzmyl&ouml;sung hat eine Aktivit&auml;t von 1 U/L. Die Konzentration des reinen Enzyms in der L&ouml;sung betr&auml;gt 0.02 Mikromol/L. Wie gross ist die molekulare Aktivit&auml;t des Enzyms?', ['0.1 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['1 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['5 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['50 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], ['100 min<sup>-1</sup>', ' 1 umol/L×min geteilt durch 0.02 umol/L = 50 1/min'], 'D', 0, 'none' ]) ;
  load_question(['Welche Informationen sind unerl&auml;sslich, um einen Stoffwchselweg zu beschreiben?', ['E.C. Nummern der beteiligten Enzyme', ' '], ['Reihenfolge der einzelnen Reaktionsschritte', ' '], ['enzymatische Mechanismen aller Reaktionsschritte', ' '], ['Regulation aller Reaktionsschritte', ' '], ['optimale pH-Werte aller Reaktionsschritte', ' '], 'B', 0, 'none' ]) ;
  load_question(['Welche Differenz der freien Enthalpie wird vom Enzym erniedrigt?', ['<img src="testbilder/delta.gif">G zwischen S und P', ' '], ['<img src="testbilder/delta.gif">G zwischen E + S und ES', ' '], ['<img src="testbilder/delta.gif">G zwischen E + S und ES<sup>#</sup>', ' '], ['<img src="testbilder/delta.gif">G zwischen E + P und EP', ' '], ['<img src="testbilder/delta.gif">G zwischen E und E<sup>#</sup>', ' '], 'C', 0, 'none' ]) ;
  load_question(['Wie nennt man das Enzym, von dem alle Nichtproteinteile entfernt worden sind?', ['Holoenzym', ' '], ['Zymogen', ' '], ['Proenzym', ' '], ['Coenzym', ' '], ['Apoenzym', ' '], 'E', 0, 'none' ]) ;
  load_question(['Welche Aussage ist <span class="fett">falsch</span>?', ['K<sub>m</sub> = [S] bei V<sub>max</sub>/2', ' '], ['V<sub>max</sub> = v bei [S] >> K<sub>m</sub>', ' '], ['Anfangsgeschwindigkeit = v bei [S] << K<sub>m</sub>', ' '], ['MM-Gleichung gilt nur f&uuml;r Anfangsgeschwindigkeiten', ' '], ['MM-Gleichung gilt nur f&uuml;r [ES] = konstant', ' '], 'C', 0, 'none' ]) ;
  load_question(['Welches ist der Wert des Schnittpunkts mit der X-Achse in einer Lineweaver-Burk Darstellung, welche mit der nebenstehenden Gleichung beschrieben wird?', ['1/V<sub>max</sub>', ' '], ['-1/V<sub>max</sub>', ' '], ['1/K<sub>m</sub>', ' '], ['-1/K<sub>m</sub>', ' '], ['K<sub>m</sub>/V<sub>max</sub>', ' '], 'D', 0, 'testbilder/gle0710.gif' ]) ;
  load_question(['Wie gross ist v einer Enzymreaktion mit MM-Mechanismus, wenn [S] = 5K<sub>m</sub>?', ['5/4 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['4/5 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['6/4 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['4/6 V<sub>max</sub>', ' S = 5×Km in MM-Gleichung einsetzen, gibt die richtige Lösung '], ['5/6 V<sub>max</sub>', ' '], 'E', 0, 'none' ]) ;
  load_question(['Zu welcher Gr&ouml;sse ist die Geschwindigkeit einer Enzymreaktion linear proportional?', ['-<img src="testbilder/delta.gif">G/RT', ' '], ['<img src="testbilder/delta.gif">G<sup>#</sup>/RT', ' '], ['exp(<img src="testbilder/delta.gif">G<sup>#</sup>/RT)', ' '], ['exp(-<img src="testbilder/delta.gif">G<sup>#</sup>/RT)', ' '], ['ln(<img src="testbilder/delta.gif">G<sup>#</sup>/RT)', ' '], 'D', 0, 'none' ]) ;
  load_question(['Eine Enzymreaktion braucht ATP als Substrat. AMP ist ein kompetitiver Inhibitoren der Reaktion, Adenosin hemmt die Reaktion nicht. Welche Folgerung kann man aus dieser Beobachtung schliessen?', ['Adenosin ist zu gross, um an die aktive Stelle zu binden', ' '], ['Adenosin bindet ausserhalb der aktiven Stelle', ' '], ['Der Ribosering ist f&uuml;r die Hemmung n&ouml;tig', ' '], ['Die Phosphatgruppe ist f&uuml;r die Hemmung n&ouml;tig', ' '], ['Adenin ist f&uuml;r die Hemmung n&ouml;tig', ' '], 'D', 0, 'none' ]) ;
  load_question(['Welche Kurve beschriebt eine Reaktion mit positiver Kooperativit&auml;t?', ['gr&uuml;n', ' '], ['schwarz', ' '], ['gelb', ' '], ['rot', ' '], ['blau', ' '], 'D', 0, 'testbilder/070117.gif' ]) ;
  load_question(['Zu welcher Klasse geh&ouml;rt das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'E', 0, 'testbilder/070108.gif' ]) ;
  load_question(['Zu welcher Klasse geh&ouml;rt das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'D', 0, 'testbilder/070109.gif' ]) ;
  load_question(['Zu welcher Klasse geh&ouml;rt das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'A', 0, 'testbilder/070110.gif' ]) ;
  load_question(['Zu welcher Klasse geh&ouml;rt das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Ligasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'C', 0, 'testbilder/070112.gif' ]) ;
  load_question(['Zu welcher Klasse geh&ouml;rt das Enzym, welches diese Reaktion katalysiert?', ['Hydrolasen', ' '], ['Oxidoreduktasen', ' '], ['Isomerasen', ' '], ['Lyasen', ' '], ['Transferasen', ' '], 'B', 0, 'testbilder/070113.gif' ]) ;
  load_question(['Welche Funktionen &uuml;ben Coenzyme und prosthetische Gruppen aus?', ['Wasserstoff&uuml;bertragung bei Redoxreaktionen', ' '], ['Elektronen&uuml;bertragung bei Redoxreaktionen', ' '], ['Decarboxylierungs- und Carboxylierungsreaktionen', ' '], ['&Uuml;bertragung von Alkyl- und Acylgruppen', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['Welches Coenzym ist an Redoxreaktionen beteiligt?', ['Nicotinamidadenindinucleotid', ' '], ['Pyridoxalphosphat', ' '], ['Flavinadenindinucleotid', ' '], ['Coenzym A', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Alkoholdehydrogenase (ADH) kommt sowohl in der menschlichen Leber als auch in der Hefe vor. Welche Aussage trifft zu?', ['1. In der Leber ist die bevorzugte Reaktionsrichtung Ethylalkohol <img src="testbilder/pfeilrechts.gif"> Acetaldehyd', ' '], ['2. Die ADH der Leber beschleunigt nur die Reaktion Ethylalkohol <img src="testbilder/pfeilrechts.gif"> Acetaldehyd', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['3. In der Hefe ist die bevorzugte Reaktionsrichtung Acetaldehyd <img src="testbilder/pfeilrechts.gif"> Ethylalkohol', ' '], ['4. Die ADH der Hefe beschleunigt nur die Reaktion Acetaldehyd <img src="testbilder/pfeilrechts.gif"> Ethylalkohol', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber Isoenzyme ist richtig?', ['Sie k&ouml;nnen fast gleiche pI aufweisen', ' '], ['Sie k&ouml;nnen sehr &auml;hnliche Aminos&auml;urensequenzen haben', ' '], ['Sie k&ouml;nnen fast dasselbe Molekulargewicht haben', ' '], ['Sie k&ouml;nnen im gleichen Gewebe vorkommen', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber Isoenzyme ist richtig?', ['Sie k&ouml;nnen sehr unterschiedliche Aminos&auml;urensequenzen haben', ' '], ['Sie k&ouml;nnen sehr unterschiedliche Molekulargewichte haben', ' '], ['Sie k&ouml;nnen aus mehreren Untereinheiten bestehen', ' '], ['Sie k&ouml;nnen in verschiedenen Spezies vorkommen', ' Isoenzyme kommen definitionsgemäss immer in derselben Spezies vor'], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Die Y-Achse zeigt die die Geschwindigkeit v einer Enzymreaktion vom MM-Typ. Welche Zuordnungen der X-Achsen sind richtig?', ['Achse 1 = [Substrat], Achse 2 = [Enzym], Achse 3 = pH', ' '], ['Achse 1 = [Coenzym], Achse 2 = [Enzym], Achse 3 = Temperatur', ' '], ['Achse 1 = [Enzym], Achse 2 = [Substrat], Achse 3 = pH', ' '], ['Achse 1 = [Substrat], Achse 2 = [Enzym], Achse 3 = Temperatur', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'testbilder/070114.gif' ]) ;
  load_question(['Die Seitenkette welcher Aminos&auml;ure kann an einer S&auml;ure-Basen Katalyse teilnehmen?', ['His', ' '], ['Leu', ' '], ['Asp', ' '], ['Ala', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage zum &Uuml;bergangszustand einer Enzymreaktion ist richtig?', ['er ist sehr kurzlebig', ' '], ['seine Konzentration ist verschwindend klein', ' '], ['er ist verschieden vom &Uuml;bergangszustand der nichtkatalysierten Reaktion', ' '], ['er hat eine h&ouml;here freie Energie als S und P', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['Welche Faktoren beeinflussen V<sub>max</sub> einer Enzymreaktion?', ['pH', ' '], ['Temperatur', ' '], ['Enzymkonzentration', ' '], ['Substratkonzentration', ' Vmax ist erreicht, wenn [S] unendlich gross, demzufolge kann [S] Vmax nicht beeinflussen '], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Faktoren beeinflussen K<sub>m</sub> einer Enzymreaktion?', ['pH', ' '], ['Substratkonzentration', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['Temperatur', ' '], ['Enzymkonzentration', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Die Summe welcher Konzentrationen bleibt im Verlauf einer Enzymreaktion, die bis zur Einstellung des thermodynamischen Gleichgewichts abl&auml;uft, konstant?', ['[E] + [ES]', ' '], ['[E] + [P]', ' '], ['[EP] + [P]', ' '], ['[S] + [P]', ' '], ['', ' '], ['0', '0', '0', '1'], 6, 'none' ]) ;
  load_question(['Welche Annahme liegt dem Michaelis-Menten-Mechanismus zugrunde?', ['v = Anfangsgeschwindigkeit', ' '], ['d[ES]/dt = 0', ' '], ['[S] >> [E]', ' '], ['T = 37 °C', ' '], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber ein kooperativ reguliertes Enzyms ist richtig?', ['v = f([S]) hat stets die Form einer Hyperbel', ' '], ['positive Kooperativit&auml;t verst&auml;rkt die Bindung des Substrats', ' '], ['negative Kooperativit&auml;t verhindert die Bindung des Substrats', ' '], ['das Enzym hat meist mehrere Untereinheiten ', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber allosterisch regulierte Enzyme ist richtig?', ['sie besitzen mindestens 2 Untereinheiten', ' '], ['ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat', ' '], ['ein heterotroper allosterischer Inhibitor bindet an einem anderen Ort als das Substrat', ' '], ['ein homotroper allosterischer Inhibitor verdr&auml;ngt das Substrat aus der Bindungsstelle', ' ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat, er bindet aber an eine regulatorische Stelle und nicht an die Substratbindungsstelle'], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber allosterisch regulierte Enzyme ist richtig?', ['sie kommen in zwei unterschiedlichen Konformationen, T und S, vor', ' '], ['ein allosterischer Regulator &auml;ndert das Verh&auml;ltnis T/S', ' '], ['T- und S-Form binden das Substrat unterschiedlich stark', ' '], ['R&uuml;ckkopplungshemmung ben&ouml;tigt mindestens ein allosterisch reguliertes Enzym', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['ATP hemmt die Reaktion Glucose + ATP <img src="testbilder/pfeilrechts.gif"> Glucose-6-Phosphat + ADP.<br>Welche Aussage ist richtig?', ['ATP ist ein homotroper allosterischer Inhibitor', ' '], ['ATP ist ein heterotroper allosterischer Inhibitor', ' '], ['ATP ist ein Substrat', ' '], ['ATP ist ein kompetitiver Inhibitor', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber die Zymogenaktivierung ist <span class="fett">falsch</span>', ['sie kommt nur bei Enzymen im Magendarmtrakt vor', ' '], ['sie verhindert die vorzeitige Aktivierung des Enzyms', ' '], ['sie dient der Inaktivierung eines Enzyms', ' '], ['sie ist reguliert', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['a) Katabole und anabole Stoffwechselwege sind in der Regel identisch,<br><br>weil<br><br>b) sie von denselben Enzymen katalysiert werden.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' wenn es so wäre, könnten Auf- und Abbau nicht reguliert werden'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'E', 2, 'none' ]) ;
  load_question(['a) Erkenntnisse &uuml;ber die Katalyse von chemischen Reaktionen sind auf Enzymreaktionen nicht anwendbar,<br><br>weil<br><br>b) chemische Katalysatoren keine Proteine sind.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Die Aktivit&auml;t eines Enzyms kann durch Phosphorylierung von Ser kontrolliert werden,<br><br>weil<br><br>b) Ser an der aktiven Stelle von Enzymen vorkommen kann.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) Enzyme zeigen ein pH-Optimum der Aktivit&auml;t,<br><br>weil<br><br>b) die Enzymaktivit&auml;t vom Ladungszustand des Substrats und der aktiven Stelle abh&auml;ngt.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'A', 2, 'none' ]) ;
  load_question(['a) Phosphorylierung eines Enzyms kann die Aktivit&auml;t erh&ouml;hen oder erniedrigen,<br><br>weil<br><br>b) die Phosphatgruppe durch Phosphatase wieder abgespalten werden kann.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) ATP ist ein Feedback-Inhibitor der Glykolyse,<br><br>weil<br><br>b) ATP alle Schritte der Gykolyse allosterisch hemmt.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'C', 2, 'none' ]) ;
  
}