// Fragen Editor 1.1

function get_questions() {

  load_question(['a) Die Zusammensetzung der inneren und &auml;usseren Lipidschicht ist unterschiedlich,<br><br>weil<br><br>b) die Lipide die Lipidschicht leicht wechseln k&ouml;nnen.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'C', 1, 'none' ]) ;
  load_question(['a) Transmembranproteine sind &uuml;ber einen GPI-Anker mit der Lipidschicht verbunden,<br><br>weil<br><br>b) Transmembranproteine nur mit Detergenzien aus der Lipiddoppelschicht herausgel&ouml;st werden k&ouml;nnen.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' GPI-verankerte Proteine durchdringen die Membran in der Regel nicht'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' GPI-verankerte Proteine durchdringen die Membran in der Regel nicht'], ['a richtig, b falsch', ' GPI-verankerte Proteine durchdringen die Membran in der Regel nicht'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Das Innere von Transmembranproteinen ist viel hydrophober als das Innere von wasserl&ouml;slichen, globul&auml;ren Proteinen,<br><br>weil<br><br>b) sie die Lipiddoppelschicht durchdringen.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a richtig, b falsch', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a falsch, b richtig', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], ['a falsch, b falsch', ' Transmembranproteine durchdringen die Lipiddoppelschicht und sind deshalb aussen hydrophob. '], 'D', 2, 'none' ]) ;
  load_question(['Welche Geschwindigkeit trifft am ehesten zu f&uuml;r die Drehung von Lipiden in der Lipiddoppelschicht bei 37 °C?', ['10<sup>2</sup> pro Sekunde', ' '], ['10<sup>5</sup> pro Sekunde', ' '], ['10<sup>9</sup> pro Sekunde', ' '], ['10<sup>12</sup> pro Sekunde', ' '], ['10<sup>16</sup> pro Sekunde', ' '], 'C', 0, 'none' ]) ;
  load_question(['Wieviele Aminos&auml;uren lang muss eine alpha-Helix sein, damit sie eine 30 Angstr&ouml;m dicke Lipiddoppelschicht durchdringt?', ['5', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['10', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['15', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['20', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], ['25', ' Ganghöhe = 5.4 Angström, 3.6 AS pro Umdrehung: 30×3.6/5.4 = 20 '], 'D', 0, 'none' ]) ;
  load_question(['FRAP-Experimente (fluorescence recovery after photobleaching) zeigen, dass', ['verschiedene Zellen miteinander fusionieren k&ouml;nnen', ' '], ['Proteine asymmetrisch angeordnet sind', ' '], ['Lipide nicht schnell zwischen der inneren und &auml;usseren Schicht austauschen', ' '], ['Proteine in der Lipiddoppelschicht lateral beweglich sind', ' '], ['Proteine die Membran durchdringen', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welches Lipid ist ein typischer Bestandteil von biologischen Membranen?', ['Cholesterin', ' '], ['Phosphatidylcholin', ' '], ['Cerebrosid', ' '], ['Chols&auml;ure', ' Cholsäure ist amphiphil und kann als Detergens Membranen auflösen!'], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welches Lipid kommt in biologischen Membranen &uuml;blicherweise nicht vor?', ['1, 2, und 3 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['1 und 3 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['2 und 4 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['4 trifft zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['1, 2, 3 und 4 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], 'C', 1, 'testbilder/040103.gif' ]) ;
  load_question(['Wie k&ouml;nnen Membranproteine die Lipiddoppelschicht durchqueren?', ['als <img src="testbilder/alpha.gif">-Helix', ' '], ['als gestreckte Peptidkette', ' '], ['als <img src="testbilder/beta.gif">-Faltblatt', ' '], ['&uuml;ber einen GPI-Anker', ' Proteine mit einem GPI-Anker sitzen meistens aussen an der Membran'], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Erythrocyten werden mit einem f&uuml;r Zucker spezifischen Reagens behandelt. Welche Proteine werden dadurch chemisch modifiziert?', ['Transmembranproteine', ' '], ['Proteine auf der Innenseite der Membran', ' '], ['Proteine auf der Aussenseite der Membran', ' '], ['Alle Membranproteine', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber Cholesterin trifft zu?', ['Es ist ein h&auml;ufiger Membranbestandteil', ' '], ['Es schr&auml;nkt die Beweglichkeit der Membranlipide ein', ' '], ['Es ist in die innere und &auml;ussere Lipidschicht eingelagert', ' '], ['Es erniedrigt die Durchl&auml;ssligkeit der Lipidschicht f&uuml;r Wasser', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['Welche Antwort zur gezeigten posttranslationellen Modifikation des N-Terms eines Proteins ist richtig? (farbige Sechsecke symbolisieren Zuckermolek&uuml;le)', ['Durch die Modifikation wird das Protein zu einem wertvolleren Nahrungsmittel', ' '], ['Durch die Modifikation wird das Protein besser wasserl&ouml;slich', ' '], ['Durch die Modifikation wird das Protein vom Immunsystem besser als ein fremdes Molek&uuml;l erkannt', ' '], ['Durch die Modifikation wird das Protein in der Lipiddoppelschicht einer Membran leichter beweglich', ' '], ['Durch die Modifikation wird das Protein in der Lipiddoppelschicht einer Membran verankert', ' '], 'E', 0, 'testbilder/GPI-anker-stryer.gif' ]) ;
  load_question(['Welche Aussage &uuml;ber die gezeigte Fluidit&auml;tskurve einer Lipiddoppelschicht ist richtig? ', ['Unges&auml;ttigte Fetts&auml;uren erh&ouml;hen Tm', ' '], ['Cis-Doppelbindungen erniedrigen Tm', ' '], ['Cholesterin hat keinen Einfluss auf Tm', ' '], ['Tm der Lipiddoppelschicht eines Erythrozyten ist tiefer als 37 °C', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'testbilder/fluidity2-stryer.gif' ]) ;
  load_question(['Welche Aussage &uuml;ber Porin ist richtig? ', ['Es ist ein Transmembranprotein', ' '], ['Es besteht aus polaren und apolaren Aminos&auml;uren', ' '], ['In den Str&auml;ngen des beta-Faltblatts alternieren polare und apolare Aminos&auml;uren', ' '], ['Die polaren Aminos&auml;uren sind vorwiegend gegen das Innere des Porinmolek&uuml;ls gerichtet ', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'testbilder/voet1128a.jpg' ]) ;
  
}