// Fragen Editor mytest

function get_questions() {

  //load_question(['Frage ', ['Antwort 1', ' '], ['Antwort 2', ' '], ['Antwort 3', ' '], ['Antwort 4', ' '], [''], ['0', '0', '0', '0'], 6, 'none' ]) ;


  // fragen mzbbm1u2
  load_question(['Projiziert man die molekularen Gr&oouml;ssenverhältnisse auf uns vertraute Dimensionen, so erhält man erstaunliche Resultate. Der Durchmesser eines Wassermoleküls sei 1 cm anstatt 0.3 nm. Welche der folgenden Grössen ist richtig?<br>1. typisches Proteinmolekül = 20 cm<br>2. Mitochondrium = 30 m<br>3. Leberzelle = 300 m<br>4. erwachsener Mensch = 60’000 km', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  //load_question(['Projiziert man die molekularen Gr&oouml;ssenverhältnisse auf uns vertraute Dimensionen, so erhält man erstaunliche Resultate. Der Durchmesser eines Wassermoleküls sei 1 cm anstatt 0.3 nm. Welche der folgenden Grössen ist richtig? ', ['typisches Proteinmolekül = 20 cm', ' '], ['Mitochondrium = 30 m', ' '], ['Leberzelle = 300 m', ' '], ['erwachsener Mensch = 60’000 km', ' '], [''], ['1', '1', '1', '1'], 6, 'none' ]) ;

  load_question(['Der Molekülbegriff wird in der Biochemie grosszügig interpretiert. Welche Aussage kann für ein Molekül im biochemischen Sinn zutreffen?<br> 1. Das Molekül besteht ausschliesslich aus Atomen, die nicht über Atombindungen (= kovalente Bindungen) miteinander verknüpft sind.<br> 2. Das Molekül besteht ausschliesslich aus Atomen, die miteinander über Atombindungen (= kovalente Bindungen) verknüpft sind.<br> 3. Atome werden durch Kräfte zusammengehalten, die in Molekülen der unbelebten Materie nicht vorkommen.<br> 4. Die meisten Atome des Moleküls werden durch Atombindungen (= kovalente Bindungen) zusammengehalten, einige aber auch durch nicht-kovalente Bindungen.<br>', ['1, 2 und 3 sind richtig', ' 1. Moleküle, in denen keine Atombindungen vorkommen, gibt es nicht.'], ['1 und 3 sind richtig', '1. Moleküle, in denen keine Atombindungen vorkommen, gibt es nicht. 3. Für die belebte Natur und die tote Materie gelten die gleichen physikalischen und chemischen Gesetze!'], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' Auch Aussage 2 ist richtig, es ist die chemische Definition eines Moleküls.'], ['alle sind richtig', ' 1. Moleküle, in denen keine Atombindungen vorkommen, gibt es nicht. 3. Für die belebte Natur und die tote Materie gelten die gleichen physikalischen und chemischen Gesetze!'], 'C', 1, 'none' ]) ;
  load_question(['Welche Substanzen zählt man zu den biologischen Makromolekülen?<br><br>1. Aminosäuren <br>2. Proteine <br>3. Vitamin C<br>4. Stärke', ['1, 2 und 3 sind richtig', ' Aminosäuren sind zwar Bausteine der Proteine, selbst aber keine Makromoleküle. Vitamin C ist ein kleines Molekül.'], ['1 und 3 sind richtig', ' Aminosäuren sind zwar Bausteine der Proteine, selbst aber keine Makromoleküle. Vitamin C ist ein kleines Molekül.'], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' auch Proteine sind Biomakromoleküle'], ['alle sind richtig', ' Aminosäuren sind zwar Bausteine der Proteine, selbst aber keine Makromoleküle. Vitamin C ist ein kleines Molekül.'], 'C', 1, 'none' ]) ;
  load_question(['Mit welchen Themen befasst sich die Molekulare Zellbiologie im ersten Studienjahr des Medizinstudiums? <br><br>1. Mit der Bildung und Weitergabe von Information zwischen Zellen<br>2. Mit der Struktur von Biomakromolekülen<br>3. Mit dem Auf- und Abbau von zelleigenen Stoffen <br>4. Mit der Gewinnung von Energie aus Licht', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', 'Auch die Energiegewinnung aus Licht ist ein hochinteressantes Problem der Molekularen Zellbiologie, das aber im Rahmen des Medizinstudiums nicht diskutiert werden kann. '], ['alle sind richtig', 'Auch die Energiegewinnung aus Licht ist ein hochinteressantes Problem der Molekularen Zellbiologie, das aber im Rahmen des Medizinstudiums nicht diskutiert werden kann. '], 'A', 1, 'none' ]) ;
  load_question(['Welche Aussage ist richtig?<br><br>1. Wasser ist ein gutes Lösungsmittel sowohl für positive wie für negative Ionen.<br>2. Bei pH 10 ist [OH<sup>-</sup>] = 10<sup>-3</sup> M.<br>3. Bei pH 3 ist [H<sup>+</sup>] = 10<sup>-3</sup> M<br>4. Bei pH 7 bilden Seifen in einer wässerigen Umgebung Liposomen.', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Seifen bilden Mizellen; Liposomen entstehen aus polaren Lipiden, z.B. aus Phospholipiden, siehe Kapitel '], ['1, 2, 3 und 4 treffen zu', ' Seifen bilden Mizellen; Liposomen entstehen aus polaren Lipiden, z.B. aus Phospholipiden, siehe Kapitel '], 'B', 1, 'none' ]) ;
  load_question(['Welche Substanz ist bei pH 7 polar aber ungeladen?<br><br>1. Glucose<br>2. Glycin (eine Aminosäure)<br>3. Glycerin<br>4. Stearinsäure (eine Fettsäure)', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' bei pH 7 sind Fettsäuren und Aminosäuren geladen'], ['4 trifft zu', ' bei pH 7 sind Fettsäuren deprotoniert und deshalb geladen'], ['1, 2, 3 und 4 treffen zu', ' bei pH 7 sind Fettsäuren und Aminosäuren geladen'], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage stimmt sowohl für Wasser bei 20 °C als auch für Eis bei -10 °C?<br><br>1. Die Moleküle bilden ein sich ständig sehr schnell änderndes Netzwerk von H-Bindungen.<br>2. Die Dichte beträgt 1.00 g/cm<sup>3</sup>.<br>3. Die Konzentration von [H<sup>+</sup>] ist 10<sup>-14 </sup>M.<br>4. Jedes Wassermolekül bildet in der Regel 4 H-Bindungen zu benachbarten Wassermolekülen.', ['1, 2, und 3 treffen zu', '1. gilt nur bei 20 °C. 2. gilt nur bei 4 °C. 3. gilt nur bei pH 14.'], ['1 und 3 treffen zu', ' 1. gilt nur bei 20 °C. 3. gilt nur bei pH 14.'], ['2 und 4 treffen zu', ' 2. gilt nur bei 4 °C. '], ['4 trifft zu', ' Bei jeder Temperatur können 4 -H-Brücken von einem Molekül Wasser ausgehen.'], ['1, 2, 3 und 4 treffen zu', '1. gilt nur bei 20 °C. 2. gilt nur bei 4 °C. 3. gilt nur bei pH 14.'], 'D', 1, 'none' ]) ;
  load_question(['Welche Aussage erklärt, weshalb Kochsalz in Wasser besser löslich ist als in Ethylalkohol?<br><br>1. Wasser bildet um NaCl eine Hydrathülle.<br>2. NaCl ist in Wasser vollständig dissoziiert.<br>3. NaCl bildet mit Wasser H-Bindungen<br>4. Wasser hat die höhere Dielektrizitätskonstante als Ethylalkohol.', ['1, 2, und 3 treffen zu', ' 1. NaCl kommt in Wasser nicht als Molekül vor, sondern als vollständig dissoziiertes Salz. 3. Na+ und Cl- bilden keine H-Brücken.'], ['1 und 3 treffen zu', '1. NaCl kommt in Wasser nicht als Molekül vor, sondern als vollständig dissoziiertes Salz. 3. Na+ und Cl- bilden keine H-Brücken.'], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Ja, aber auch 2. ist richtig.'], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'none' ]) ;
  load_question(['Die Seitenketten von apolaren (hydrophoben) Aminosäuren liegen mehrheitlich im Innern eines Proteins (siehe Kapitel "Proteine"). Welche Aussage trifft zu?<br> 1. Im Innern des Proteins kann leichter ein "Wasserkäfig" um die apolaren Seitenketten entstehen.<br> 2. Im Innern des Proteins bilden sich keine entropisch ungünstigen "Wasserkäfige" um die apolaren Seitenketten.<br> 3. Im Innern des Proteins können die apolaren Seitenketten leichter H-Brücken untereinander ausbilden.<br> 4. Zwischen den apolaren Seitenketten im Innern des Proteins gibt es schwache Bindungskräfte (van der Waals-Bindungen).<br>', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'C', 1, 'none' ]) ;

  // fragen mzbbm4a
    load_question(['Welche Eigenschaft ist den 4 Substanzen gemeinsam?<br><br>1. Es sind Alkohole<br>2. Sie kommen als Bestandteile von Glykolipiden vor<br>3. Sie kommen als Bestandteile von Phospholipiden vor<br>4. Sie kommen als Bestandteile von Terpenen vor', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'testbilder/040107.gif' ]) ;
  load_question(['Welche Fetts&auml;ure ist unges&auml;ttigt?<br><br>1. Palmitins&auml;ure<br>2. &Ouml;ls&auml;ure<br>3. Stearins&auml;ure<br>4. Arachidons&auml;ure', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'none' ]) ;
  load_question(['Welches Lipid ist eine amphiphile Substanz?<br><br>1. Cholesterin<br>2. Vitamin K<br>3. Prostaglandin<br>4. Gallens&auml;ure', ['1, 2, und 3 treffen zu', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], ['1 und 3 treffen zu', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], ['2 und 4 treffen zu', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], ['4 trifft zu', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], ['1, 2, 3 und 4 treffen zu', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], 'D', 1, 'none' ]) ;

  // mzbbm4b
  load_question(['a) Die Zusammensetzung der inneren und äusseren Lipidschicht ist unterschiedlich,<br><br>weil<br><br>b) die Lipide die Lipidschicht leicht wechseln können.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'C', 1, 'none' ]) ;
  load_question(['FRAP-Experimente (fluorescence recovery after photobleaching) zeigen, dass', ['verschiedene Zellen miteinander fusionieren können', ' '], ['Proteine asymmetrisch angeordnet sind', ' '], ['Lipide nicht schnell zwischen der inneren und äusseren Schicht austauschen', ' '], ['Proteine in der Lipiddoppelschicht lateral beweglich sind', ' '], ['Proteine die Membran durchdringen', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welches Lipid ist ein typischer Bestandteil von biologischen Membranen?<br><br>1. Cholesterin<br>2. Phosphatidylcholin<br>3. Cerebrosid<br>4. Cholsäure', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Cholsäure ist amphiphil und kann als Detergens Membranen auflösen!'], ['1, 2, 3 und 4 treffen zu', ' Cholsäure ist amphiphil und kann als Detergens Membranen auflösen!'], 'A', 1, 'none' ]) ;
  load_question(['Welches Lipid kommt in biologischen Membranen üblicherweise nicht vor?', ['1, 2, und 3 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['1 und 3 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['2 und 4 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['4 trifft zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], ['1, 2, 3 und 4 treffen zu', ' Vitamin A (2) und Gallensäure (4) kommen in Membranen nicht vor'], 'C', 1, 'testbilder/040103.gif' ]) ;
  load_question(['Wie können Membranproteine die Lipiddoppelschicht durchqueren?<br><br>1. als <img src="testbilder/alpha.gif">-Helix<br>2. als gestreckte Peptidkette<br>3. als <img src="testbilder/beta.gif">-Faltblatt<br>4. über einen GPI-Anker', ['1, 2, und 3 treffen zu', ''], ['1 und 3 treffen zu', ''], ['2 und 4 treffen zu', 'Proteine mit einem GPI-Anker sitzen meistens aussen an der Membran'], ['4 trifft zu', 'Proteine mit einem GPI-Anker sitzen meistens aussen an der Membran'], ['1, 2, 3 und 4 treffen zu', 'Proteine mit einem GPI-Anker sitzen meistens aussen an der Membran'], 'B', 1, 'none' ]) ;
  load_question(['Erythrocyten werden mit einem für Zucker spezifischen Reagens behandelt.<br>Welche Proteine werden dadurch chemisch modifiziert?<br><br>1. Transmembranproteine<br>2. Proteine auf der Innenseite der Membran<br>3. Proteine auf der Aussenseite der Membran<br>4. Alle Membranproteine', ['1, 2, und 3 treffen zu', 'Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['1 und 3 treffen zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['2 und 4 treffen zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['4 trifft zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], ['1, 2, 3 und 4 treffen zu', ' Der Zuckeranteil der Glykoproteine schaut nach aussen'], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage über Cholesterin trifft zu?<br><br>1. Es ist ein häufiger Membranbestandteil<br>2. Es schränkt die Beweglichkeit der Membranlipide ein<br>3. Es ist in die innere und äussere Lipidschicht eingelagert<br>4. Es erniedrigt die Durchlässligkeit der Lipidschicht für Wasser', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question([' Welche Aussage über die gezeigte Fluiditätskurve einer Lipiddoppelschicht ist richtig? <br><br>1. Ungesättigte Fettsäuren erhöhen Tm<br>2. Cis-Doppelbindungen erniedrigen Tm<br>3. Cholesterin hat keinen Einfluss auf Tm<br>4. Tm der Lipiddoppelschicht eines Erythrozyten ist tiefer als 37 °C ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'C', 1, 'testbilder/fluidity2-stryer.gif' ]) ;
  load_question(['Welche Aussage über Porin ist richtig? <br><br>1. Es ist ein Transmembranprotein<br>2. Es besteht aus polaren und apolaren Aminosäuren<br>3. In den Strängen des beta-Faltblatts alternieren polare und apolare Aminosäuren<br>4. Die polaren Aminosäuren sind vorwiegend gegen das Innere des Porinmoleküls gerichtet ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'E', 1, 'testbilder/voet1128a.jpg' ]) ;

  // mzbbm5
  load_question(['Welche Aussage über Glykoproteine trifft zu?<br><br>1. Zucker und Protein sind über elektrostatische Kräfte aneinander gebunden<br>2. sie enthalten viele repetitive Disaccharideinheiten<br>3. sie binden viel Wasser<br>4. sie kommen vorwiegend extrazellulär vor', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welche Aussage ist richtig?<br><br>1. Der Zuckeranteil ist bei Glykoproteinen geringer als bei Proteoglykanen<br>2. Amylose ist ein unverzweigtes Homoglykan<br>3. Inulin passiert die Glomerulusmembran ungehindert<br>4. Cellulose ist eine wichtige Energiequelle bei vegetarischer Ernährung', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Welche der folgenden Verbindungen ist ein Polysaccharid?<br><br>1. Hyaluronsäure<br>2. <img src="testbilder/beta.gif">-Carotin<br>3. Heparin<br>4. Keratin', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question([' Wo kommt das gezeigte Molekül vor?<br><br>1. in Stärke<br>2. in sauren Mucopolysacchariden<br>3. in Glykoproteinen<br>4.in Glycosaminoglykanen ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'C', 1, 'testbilder/heparin.jpg' ]) ;

  // mzbbm6
  load_question(['Welche Aussage über <img src="testbilder/delta.gif">G ist richtig?<br><br>1. <img src="testbilder/delta.gif">G sagt aus, in welcher Richtung eine Reaktion spontan abläuft<br>2. <img src="testbilder/delta.gif">G sagt aus, ob eine Reaktion exotherm oder endotherm ist<br>3. <img src="testbilder/delta.gif">G ist proportional zum natürlichen Logarithmus der Gleichgewichtskonstante<br>4. <img src="testbilder/delta.gif">G ist unabhängig von der Konzentration der Edukte und Produkte der Reaktion', ['1, 2, und 3 treffen zu', ' exotherm und endotherm beziehen sich auf die Enthalpieänderung (Wärmeänderung)'], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' exotherm und endotherm beziehen sich auf die Enthalpieänderung (Wärmeänderung)'], ['4 trifft zu', ' deltaG ist konzentrationsabhängig '], ['1, 2, 3 und 4 treffen zu', ' exotherm und endotherm beziehen sich auf die Enthalpieänderung (Wärmeänderung) und deltaG ist konzentrationsabhängig'], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage über die Zustandsfunktionen der Reaktion Glucose <img src="testbilder/pfeilrechts.gif"> 6 CO<sub>2</sub> + 6 H<sub>2</sub>O ist <span class="fett">falsch</span>?<br><br>1. sie sind abhängig von den Konzentrationen von Glucose, CO<sub>2</sub> und H<sub>2</sub>O<br>2. sie sind abhängig von der Temperatur<br>3. sie sind Abhängig vom Druck<br>4. sie sind abhängig von der Anzahl der Zwischenprodukte der Reaktion', ['1, 2, und 3 treffen zu', ' Zustandsfunktionen sind abhängig vom Anfangs- und Endzustand der Reaktion'], ['1 und 3 treffen zu', ' Zustandsfunktionen sind abhängig vom Anfangs- und Endzustand der Reaktion'], ['2 und 4 treffen zu', ' Zustandsfunktionen sind abhängig vom Anfangs- und Endzustand der Reaktion'], ['4 trifft zu', ' Zustandsfunktionen sind unabhängig vom Reaktionsweg'], ['1, 2, 3 und 4 treffen zu', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welche Bedingung gilt für <img src="testbilder/delta.gif">G° der Reaktion <span class="kursiv">A + B </span><img src="testbilder/pfeildoppel.gif"><span class="kursiv"> C + D?</span><br><br>1. [A] = [B] = [C] = [D] = 1 M<br>2. T = 25 °C<br>3. pH = 0<br>4. p = 1 atm', ['1, 2, und 3 treffen zu', ' '], ['1 ud 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welche Feststellung über die gekoppelten Reaktionen ist richtig?<br><br>Phosphoenolpyruvat + H<sub>2</sub>O <img src="testbilder/pfeilrechts.gif"> Pyruvat + P<sub>a</sub>   <img src="testbilder/delta.gif">G°’ = -61.9 kJ mol<sup>-1</sup><br>ATP + H<sub>2</sub>O <img src="testbilder/pfeilrechts.gif"> ADP + P<sub>a</sub>    <img src="testbilder/delta.gif">G°’ = -30.5 kJ mol<sup>-1</sup><br><br>1. Unter Standardbedingungen läuft die Reaktion Phosphoenolpyruvat + ADP <img src="testbilder/pfeilrechts.gif"> Pyruvat + ATP spontan ab<br>2. Die Reaktion Phosphoenolpyruvat + ADP <img src="testbilder/pfeilrechts.gif"> Pyruvat + ATP wird unter allen Bedingungen spontan ablaufen<br>3. Die Reaktion Phosphoenolpyruvat + ADP <img src="testbilder/pfeilrechts.gif"> Pyruvat + ATP wird spontan ablaufen, wenn [Pyruvat][ATP]/[Phosphoenolpyruvat][ADP] kleiner als die Gleichgewichtskonstante K ist<br>4. Unter Standardbedingungen läuft die Reaktion Pyruvat + ATP <img src="testbilder/pfeilrechts.gif"> Phosphoenolpyruvat + ADP spontan ab', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Wie lässt sich die Richtung der Reaktion A <img src="testbilder/pfeilrechts.gif"> B, für die <img src="testbilder/delta.gif">G°’ = -5 kJ/mol beträgt, umkehren?<br><br>1. durch Erhöhen der Konzentration von B<br>2. durch eine sehr lange Reaktionsdauer<br>3. durch kontinuierliches Entfernen von A<br>4. durch Zugabe eines Katalysators', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' ein Katalysator kann die freie Enthalpie nicht verändern'], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage ist richtig?<br><br>1. ATP wird in derjenigen Zelle verbraucht, in der es gebildet wird<br>2. In der Zelle sind Synthese und Verbrauch von ATP aufeinander abgestimmt<br>3. ATP kann durch eine Reaktion, deren <img src="testbilder/delta.gif">G etwa null ist, in andere Nukleosidtriphosphate umgewandelt werden<br>4. Die Hydrolyse von ATP ist unter allen Bedingungen exergonisch', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Welche Aussage über die Reaktion AMP + ATP <img src="testbilder/pfeildoppel.gif"> ADP + ADP ist richtig?<br><br>1. sie ist stark exergonisch<br>2. sie ist stark endergonisch<br>3. es handelt sich um eine Esterbildung bezw. -hydrolyse<br>4. sie wird durch das Enzym Adenylatkinase (Myokinase) katalysiert', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welche Aussage über eine Redoxreaktion ist richtig?<br><br>1. Eine Redoxreaktion mit einem negativen <img src="testbilder/delta.gif">E hat ein positives <img src="testbilder/delta.gif">G<br>2. Im thermodynamischen Gleichgewicht ist <img src="testbilder/delta.gif">G = 0<br>3. Im thermodynamischen Gleichgewicht ist die <img src="testbilder/delta.gif">E = 0<br>4. Im thermodynamischen Gleichgewicht sind die Geschwindigkeiten der Hin- und Rückreaktion null', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Welche Aussage über <img src="testbilder/delta.gif">G°’ ist richtig?<br><br>1. <img src="testbilder/delta.gif">G°’ gilt für pH 7<br>2. <img src="testbilder/delta.gif">G°’ ist abhängig von den Konzentrationen der Edukte und Produkte<br>3. <img src="testbilder/delta.gif">G°’ hat die Dimension J/mol<br>4. <img src="testbilder/delta.gif">G°’ ist stets grösser als <img src="testbilder/delta.gif">G', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['In der Glykolyse sind folgende drei Reaktionen miteinander gekoppelt zu einer Reaktion mit <img src="testbilder/delta.gif">G = -16 kJ/mol.<br>Welche Aussage über die gekoppelte Reaktion ist richtig?<br><br>1. sie lautet GAP + P<sub>a</sub> + ADP + NAD<sup>+</sup> <img src="testbilder/pfeilrechts.gif"> 3PG + ATP + NADH + H<sup>+</sup><br>2. die gekoppelte Reaktion läuft spontan ab<br>3. im Gleichgewicht ist [ATP] > [ADP]<br>4. im Gleichgewicht ist [BPG] = 0', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'testbilder/060101.gif' ]) ;

	// mzbbm7
   load_question(['Welche Funktionen üben Coenzyme und prosthetische Gruppen aus?<br><br>1. Wasserstoffübertragung bei Redoxreaktionen<br>2. Elektronenübertragung bei Redoxreaktionen<br>3. Decarboxylierungs- und Carboxylierungsreaktionen<br>4. Übertragung von Alkyl- und Acylgruppen', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welches Coenzym ist an Redoxreaktionen beteiligt?<br><br>1. Nicotinamidadenindinucleotid<br>2. Pyridoxalphosphat<br>3. Flavinadenindinucleotid<br>4. Coenzym A', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Alkoholdehydrogenase (ADH) kommt sowohl in der menschlichen Leber als auch in der Hefe vor. Welche Aussage trifft zu?<br><br>1. In der Leber ist die bevorzugte Reaktionsrichtung Ethylalkohol <img src="testbilder/pfeilrechts.gif"> Acetaldehyd<br>2. Die ADH der Leber beschleunigt nur die Reaktion Ethylalkohol <img src="testbilder/pfeilrechts.gif"> Acetaldehyd<br>3. In der Hefe ist die bevorzugte Reaktionsrichtung Acetaldehyd <img src="testbilder/pfeilrechts.gif"> Ethylalkohol<br>4. Die ADH der Hefe beschleunigt nur die Reaktion Acetaldehyd <img src="testbilder/pfeilrechts.gif"> Ethylalkohol</p>', ['1, 2, und 3 treffen zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['4 trifft zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], ['1, 2, 3 und 4 treffen zu', ' ein Enzym kann das thermodynamische Gleichgweicht nicht verändern und deshalb nicht eine Reaktionsrichtung bevorzugt katalysieren'], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage über Isoenzyme ist richtig?<br><br>1. Sie können fast gleiche pI aufweisen<br>2. Sie können sehr ähnliche Aminosäurensequenzen haben<br>3. Sie können fast dasselbe Molekulargewicht haben<br>4. Sie können im gleichen Gewebe vorkommen', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welche Aussage über Isoenzyme ist richtig?<br><br>1. Sie können sehr unterschiedliche Aminosäurensequenzen haben<br>2. Sie können sehr unterschiedliche Molekulargewichte haben<br>3. Sie können aus mehreren Untereinheiten bestehen<br>4. Sie können in verschiedenen Spezies vorkommen', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Isoenzyme kommen definitionsgemäss immer in derselben Spezies vor'], ['1, 2, 3 und 4 treffen zu', ' Isoenzyme kommen definitionsgemäss immer in derselben Spezies vor'], 'A', 1, 'none' ]) ;
  load_question(['Die Y-Achse zeigt die die Geschwindigkeit v einer Enzymreaktion vom MM-Typ.<br> Welche Zuordnungen der X-Achsen sind richtig?<br><br>1. Achse 1 = [Substrat], Achse 2 = [Enzym], Achse 3 = pH<br>2. Achse 1 = [Coenzym], Achse 2 = [Enzym], Achse 3 = Temperatur<br>3. Achse 1 = [Enzym], Achse 2 = [Substrat], Achse 3 = pH<br>4. Achse 1 = [Substrat], Achse 2 = [Enzym], Achse 3 = Temperatur', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'testbilder/070114.gif' ]) ;
  load_question(['Die Seitenkette welcher Aminosäure kann an einer Säure-Basen Katalyse teilnehmen?<br><br>1. His<br>2. Leu<br>3. Asp<br>4. Ala', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Welche Aussage zum Übergangszustand einer Enzymreaktion ist richtig?<br><br>1. er ist sehr kurzlebig<br>2. seine Konzentration ist verschwindend klein<br>3. er ist verschieden vom Übergangszustand der nichtkatalysierten Reaktion<br>4. er hat eine höhere freie Energie als S und P', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welche Faktoren beeinflussen V<sub>max</sub> einer Enzymreaktion?<br><br>1. pH<br>2. Temperatur<br>3. Enzymkonzentration<br>4. Substratkonzentration<br>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Vmax ist erreicht, wenn [S] unendlich gross, demzufolge kann [S] Vmax nicht beeinflussen '], ['1, 2, 3 und 4 treffen zu', ' Vmax ist erreicht, wenn [S] unendlich gross, demzufolge kann [S] Vmax nicht beeinflussen '], 'A', 1, 'none' ]) ;
  load_question(['Welche Faktoren beeinflussen K<sub>m</sub> einer Enzymreaktion?<br><br>1. pH<br>2. Substratkonzentration<br>3. Temperatur<br>4. Enzymkonzentration<br>', ['1, 2, und 3 treffen zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['4 trifft zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], ['1, 2, 3 und 4 treffen zu', ' Km ist eine für das Enzym charakteristische Grösse und kann deshalb durch [S] und [E] nicht beeinflusst werden '], 'B', 1, 'none' ]) ;
  load_question(['Die Summe welcher Konzentrationen bleibt im Verlauf einer Enzymreaktion, die bis zur Einstellung des thermodynamischen Gleichgewichts abläuft, konstant?<br><br>1. [E] + [ES]<br>2. [E] + [P]<br>3. [EP] + [P]<br>4. [S] + [P]', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welche Annahme liegt dem Michaelis-Menten-Mechanismus zugrunde?<br><br>1. v = Anfangsgeschwindigkeit<br>2. d[ES]/dt = 0<br>3. [S] >> [E]<br>4. T = 37 °C', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Welche Aussage über ein kooperativ reguliertes Enzyms ist richtig?<br><br>1. v = f([S]) hat stets die Form einer Hyperbel<br>2. positive Kooperativität verstärkt die Bindung des Substrats<br>3. negative Kooperativität verhindert die Bindung des Substrats<br>4. das Enzym hat meist mehrere Untereinheiten </p>', ['1, 2, und 3 treffen zu', ' negative Kooperativität zeigt keine Hyperbel und bewirkt nur, dass S schlechter bindet'], ['1 und 3 treffen zu', ' negative Kooperativität zeigt keine Hyperbel und bewirkt nur, dass S schlechter bindet'], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' negative Kooperativität zeigt keine Hyperbel und bewirkt nur, dass S schlechter bindet'], 'C', 1, 'none' ]) ;
  load_question(['Welche Aussage über allosterisch regulierte Enzyme ist richtig?<br><br>1. sie besitzen mindestens 2 Untereinheiten<br>2. ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat<br>3. ein heterotroper allosterischer Inhibitor bindet an einem anderen Ort als das Substrat<br>4. ein homotroper allosterischer Inhibitor verdrängt das Substrat aus der Bindungsstelle', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat, er bindet aber an eine regulatorische Stelle und nicht an die Substratbindungsstelle'], ['1, 2, 3 und 4 treffen zu', ' ein homotroper allosterischer Inhibitor ist identisch mit dem Substrat, er bindet aber an eine regulatorische Stelle und nicht an die Substratbindungsstelle'], 'A', 1, 'none' ]) ;
  load_question(['Welche Aussage über allosterisch regulierte Enzyme ist richtig?<br><br>1. sie kommen in zwei unterschiedlichen Konformationen, T und S, vor<br>2. ein allosterischer Regulator ändert das Verhältnis T/S<br>3. T- und S-Form binden das Substrat unterschiedlich stark<br>4. Rückkopplungshemmung benötigt mindestens ein allosterisch reguliertes Enzym', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
 
}