// Fragen Editor mytest

function get_questions() {

  load_question(['Ordne die Bausteine den Biomakromolekülen zu:<br><br>A Proteine<br>B Polysaccharide<br>C Lipide<br>D DNA<br>E RNA', ['einfache Zucker (Monosaccharide)', ' '], ['Fettsäuren', ' '], ['Aminosäuren', ' '], ['Desoxyribose', ' '], ['Ribose', ' '], ['B', 'C', 'A', 'D', 'E'], 3, 'none' ]) ;
  load_question(['Ein Baum ist ein(e) ', ['Pflanze', ' '], ['Maschine', ' '], ['Einzelnes Molek&uuml;l', ' '], ['Lebewesen', ' '], [''], ['1', '0', '0', '1'], 6, 'none' ]) ;
  load_question(['Welches ist der wichtigste Grund, weshalb die Komplexität von Biomolekülen mit zunehmender Molekülmasse steigt?', ['Das grössere Molekulargewicht', ' Die Grösse des Molekulargwichts korreliert nicht mit der Komplexität eines Moleküls'], ['Die grössere Anzahl der Bausteine', 'Die grössere Anzahl der Bausteine ist noch kein Grund für die grössere Komplexität'], ['Die grössere Vielfalt der Bausteine', 'Die grössere Vielfalt ist noch kein Grund für die grössere Komplexität'], ['Die grössere Möglichkeit, die Bausteine zu kombinieren', ' '], ['Keine der obigen Antworten ist richtig', ' '], 'D', 0, 'none' ]) ;
  load_question(['Projiziert man die molekularen Gr&oouml;ssenverhältnisse auf uns vertraute Dimensionen, so erhält man erstaunliche Resultate. Der Durchmesser eines Wassermoleküls sei 1 cm anstatt 0.3 nm. Welche der folgenden Grössen ist richtig?<br>1. typisches Proteinmolekül = 20 cm<br>2. Mitochondrium = 30 m<br>3. Leberzelle = 300 m<br>4. erwachsener Mensch = 60’000 km', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['a) Wasser bildet den Hauptteil der Masse einer Zelle<br><br>weil<br><br>b) Wasser durch die Zellmembran durchtreten kann.', ['a und b richtig; b als Begründung von a richtig', ' a) und b) sind zwar richtig, das begründende "weil" macht aber keinen Sinn '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' Wasser kann die Lipiddoppelschicht passieren, zusätzlich geht Wasser durch das Membranprotein Aquaporin ins Zellinnere.'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['Benennen Sie die abgebildete Aminos&auml;ure', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Glycin', 'Gly'], 4, 'testbilder/030320.gif' ]) ;
}