// Fragen Editor 1.1

function get_questions() {

  load_question(['Machen Sie die korrekte Zuordnung.', ['Sulfhydrylgruppe', ' '], ['Amidbindung', ' '], ['Hydroxylgruppe', ' '], ['Carboxylgruppe', ' '], ['Aminogruppe', ' '], ['C', 'A', 'E', 'B', 'D'], 3, 'testbilder/030101.gif' ]) ;
  load_question(['Machen Sie die korrekte Zuordnung der eingekreisten Gruppen. Das Molek&uuml;l ist Phalloidin, das Gift des Knollenbl&auml;tterpilzes.', ['Peptidbindung Pro-Ala', ' '], ['Alkohol', ' '], ['nicht-proteinogene Aminos&auml;ure', ' '], ['Indolring', ' '], ['Thioether', ' '], ['D', 'E', 'A', 'B', 'C'], 3, 'testbilder/030102.gif' ]) ;
  load_question(['Machen Sie die korrekte Zuordnung der eingekreisten Gruppen.', ['Ketogruppe', ' '], ['sekund&auml;re Aminogruppe', ' '], ['Carbons&auml;ureester', ' '], ['Aldehyd', ' '], ['Phosphors&auml;ureanhydrid', ' '], ['A', 'C', 'B', 'E', 'D'], 3, 'testbilder/030103.gif' ]) ;
  load_question(['Ordnen Sie den pH Wert dem ungef&auml;hren Ladungszustand von Asparagins&auml;ure zu.<br><br>A Ladung etwa +2<br>B Ladung etwa +1<br>C Ladung etwa 0<br>D Ladung etwa -1<br>E Ladung etwa -2', ['pH 1.0', ' '], ['pH 3.0', ' '], ['pH 6.0', ' '], ['pH 7.0', ' '], ['pH 11', ' '], ['B', 'C', 'D', 'D', 'E'], 3, 'none' ]) ;
  load_question(['Zuordnung treffen:<br><br>A pH 1.5<br>B pH 3<br>C pH 6.6<br>D pH 7.4<br>E pH 14', ['1 M NaOH', ' '], ['Speichel', ' '], ['Blut', ' '], ['Essig', ' '], ['Magensaft', ' '], ['E', 'C', 'D', 'B', 'A'], 3, 'none' ]) ;
  load_question(['Ordnen Sie die pI-Werte den elektrophoretischen Banden zu. Die Elektrophorese wird bei pH 6.0 durchgef&uuml;hrt.', ['pI = 9.4', ' '], ['pI = 5.9', ' '], ['pI = 4.1', ' '], ['pI = 4.8', ' '], ['pI = 7.9', ' '], ['A', 'C', 'E', 'D', 'B'], 3, 'testbilder/030104.gif' ]) ;
  load_question(['Ordnen Sie die Sequenzen den elektrophoretischen Banden zu. Die Elektrophorese wird bei pH 6.0 durchgef&uuml;hrt.', ['Lys-Val-Gln-Glu-His-Asp-Leu-Ser-Thr', ' '], ['Lys-Val-Arg-Lys-His-Gln-Glu-Leu-Lys-Ser', ' '], ['Asp-Val-Glu-Glu-Ala-Asp-Leu-Ser-Thr', ' '], ['His-Val-Glu-Lys-His-Asn-Leu-Ser-Thr', ' '], ['Asp-Val-Glu-Glu-Lys-Asp-Leu-Ser-Thr', ' '], ['C', 'A', 'E', 'B', 'D'], 3, 'testbilder/030104.gif' ]) ;
  load_question(['Ordnen Sie die Strukturformeln den Aminos&auml;uren zu.', ['Ala', ' '], ['Cys', ' '], ['Gly', ' '], ['Thr', ' '], ['Val', ' '], ['A', 'C', 'E', 'B', 'D'], 3, 'testbilder/030105.gif' ]) ;
  load_question(['Ordnen Sie die Strukturformeln den Aminos&auml;uren zu.', ['Asn', ' '], ['Asp', ' '], ['Cystin', ' '], ['Ile', ' '], ['Met', ' '], ['D', 'E', 'C', 'A', 'B'], 3, 'testbilder/030106.gif' ]) ;
  load_question(['Ordnen Sie die Strukturformeln den Aminos&auml;uren zu.', ['Leu', ' '], ['Lys', ' '], ['Phe', ' '], ['Ser', ' '], ['Thr', ' '], ['E', 'C', 'D', 'B', 'A'], 3, 'testbilder/030107.gif' ]) ;
  load_question(['Ordnen Sie die Strukturformeln den Aminos&auml;uren zu.', ['Arg', ' '], ['Asn', ' '], ['His', ' '], ['Pro', ' '], ['Trp', ' '], ['A', 'E', 'B', 'D', 'C'], 3, 'testbilder/030108.gif' ]) ;
  load_question(['Ordnen Sie die Strukturformeln den Aminos&auml;uren zu.', ['Gln', ' '], ['Glu', ' '], ['Leu', ' '], ['Lys', ' '], ['Tyr', ' '], ['A', 'E', 'B', 'D', 'C'], 3, 'testbilder/030109.gif' ]) ;
  load_question(['a) Die Peptidbindung ist nicht frei drehbar<br><br>weil<br><br>b) das Amidproton nicht basisch ist.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' b) ist zwar richtig, aber keine Begründung für a)'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ''], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) Jedes Polypeptid hat eine definierte Raumstruktur<br><br>weil<br><br>b) die Raumstruktur durch die Aminos&auml;urensequenz vorgegeben ist.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' nur eine verschwindend kleine Zahl aller möglichen Polypeptide hat eine definierte Raumstruktur'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', 'b) ist zwar richtig, aber nur eine verschwindend kleine Zahl aller möglichen Polypeptide hat eine definierte Raumstruktur'], ['a richtig, b falsch', ' nur eine verschwindend kleine Zahl aller möglichen Polypeptide hat eine definierte Raumstruktur'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Met ist die einzige schwefelhaltige Aminos&auml;ure<br><br>weil<br><br>b) nur Met einen Thioether in der Seitenkette enth&auml;lt.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' auch Cys enthält Schwefel'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' auch Cys enthält Schwefel'], ['a richtig, b falsch', ' auch Cys enthält Schwefel'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Proteine mit Disulfidbr&uuml;cken kommen bevorzugt im Cytoplasma vor<br><br>weil<br><br>b) das Redoxpotential ausserhalb der Zelle stark negativ ist.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' ein stark negatives Redoxpotential begünstigt die reduzierte Form'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' ein stark negatives Redoxpotential begünstigt die reduzierte Form'], 'E', 2, 'none' ]) ;
  load_question(['a) Fibrill&auml;re Proteine sind weniger gut wasserl&ouml;slich als globul&auml;re<br><br>weil<br><br>b) sie in der Regel eine gr&ouml;ssere Masse als globul&auml;re Proteine haben.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' die grosse Masse an sich hat nichts mit der Löslichkeit zu tun'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' die grosse Masse an sich hat nichts mit der Löslichkeit zu tun'], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['Der prozentuale Anteil welches Elements ist in allen Proteinen beinahe konstant?', ['Kohlenstoff', ' '], ['Stickstoff', ' '], ['Wasserstoff', ' '], ['Sauerstoff', ' '], ['Schwefel', ' '], 'B', 0, 'none' ]) ;
  load_question(['Was f&uuml;r eine chemische Reaktion ist die Bildung von Cystin aus 2 Cysteinen?', ['Hydrolyse', ' '], ['Aldolspaltung', ' '], ['Reduktion', ' '], ['Oxidation', ' '], ['Esterbildung', ' '], 'D', 0, 'none' ]) ;
  load_question(['Wieviele unterschiedliche Sequenzen kann ein Pentapeptid aufweisen?', ['5&times;5', ' '], ['5<sup>5</sup>', ' '], ['20&times;5', ' '], ['5<sup>20</sup>', ' '], ['20<sup>5</sup>', ' '], 'E', 0, 'none' ]) ;
  load_question(['Welche Zahl entspricht am ehesten der Masse eines Proteins mit 150 Aminos&auml;uren?', ['8&rsquo;000', ' die durchschnittliche Masse einer Aminosäure ist 112'], ['11&rsquo;000', ' die durchschnittliche Masse einer Aminosäure ist 112'], ['14&rsquo;000', ' die durchschnittliche Masse einer Aminosäure ist 112'], ['17&rsquo;000', ' die durchschnittliche Masse einer Aminosäure ist 112'], ['20&rsquo;000', ' die durchschnittliche Masse einer Aminosäure ist 112'], 'D', 0, 'none' ]) ;
  load_question(['Welche Aussage trifft f&uuml;r ein Protein mit einem tiefen pI am besten zu?', ['Das Verh&auml;ltnis der sauren zu den basischen Aminos&auml;uren ist gr&ouml;sser als 1', ' '], ['Das Verh&auml;ltnis der sauren zu den basischen Aminos&auml;uren ist kleiner als 1', 'Dieses Verhältnis gilt für ein basisches Protein'], ['Es enth&auml;lt wenige saure Aminos&auml;uren', ' das ist nur richtig, wenn das Protein noch viel weniger basische Aminosäuren enthält'], ['Es enth&auml;lt wenige basische Aminos&auml;uren', 'Das genügt nicht als Begründung: das Protein muss mehr saure als basische Aminosäuren enthalten'], ['Es ist gut wasserl&ouml;slich', 'Auch basische und neutrale Proteine können gut wasserlöslich sein.'], 'A', 0, 'none' ]) ;
  load_question(['Ein Milliliter einer Proteinl&ouml;sung wird gegen 1 Liter Wasser dialysiert. Das Protein ist in 1 M NaCl gel&ouml;st. Wie gross ist die NaCl-Konzentration der Proteinl&ouml;sung nach der Dialyse?', ['0.1 M', ' '], ['0.01 M', ' '], ['0.001M', ' Rechnerisch korrekt - weil aber Proteine geladen sind, binden sie stets Salzionen, so dass nicht ganz dieselbe Salzkonzentration wie in der Dialyseflüssigkeit erreicht werden kann.'], ['0.0001 M', ' '], ['etwas mehr als 0.001 M', 'Weil Proteine geladen sind, binden sie stets Salzionen, so dass nicht ganz dieselbe Salzkonzentration wie in der Dialyseflüssigkeit erreicht werden kann.'], 'E', 0, 'none' ]) ;
  load_question(['Bei der Elektrophorese werden Molek&uuml;le aufgrund welcher Eigenschaft getrennt?', ['Gr&ouml;sse', ' '], ['Polarit&auml;t', ' '], ['Form', ' '], ['Ladung', ' '], ['Chiralit&auml;t', ' '], 'D', 0, 'none' ]) ;
  load_question(['Welche Ladung passt am besten zum Peptid Ala-Thr-Leu-Asp-His-Lys-Tyr bei pH 5?', ['+2', ' '], ['+1', ' '], ['0', ' '], ['-1', ' '], ['-2', ' '], 'B', 0, 'none' ]) ;
  load_question(['Essigs&auml;ure (HA) hat einen pK<sub>a</sub> von 4.76. Welche Aussage ist richtig bei pH 5.76?', ['[ A<sup>-</sup> ] = [ HA ]', ' '], ['[ A<sup>-</sup> ] = 10[ HA ]', ' '], ['[ A<sup>-</sup> ] = [ HA ]/10', ' '], ['[ A<sup>-</sup> ] = 2[ HA ]', ' '], ['[ A<sup>-</sup> ] = [ HA ]/2', ' '], 'B', 0, 'none' ]) ;
  load_question(['Bei welchem pH-Wert dominiert die gezeichnete Form von Glu?', ['pH 1', ' '], ['pH 4', ' '], ['pH 7', ' '], ['pH 10', ' '], ['bei keinem der obigen pH-Werte', ' '], 'E', 0, 'testbilder/030307.gif' ]) ;
  load_question(['Wie berechnet man n&auml;herungsweise den pI von Asp?', ['(pK<sub>alpha-Carboxyl </sub>+ pK<sub>Seitenkette</sub>)/2', ' '], ['(pK<sub>alpha-Amino</sub>+ pK<sub>Seitenkette</sub>)/2', ' '], ['(pK<sub>alpha-Carboxyl </sub>+ pK<sub>alpha-Amino</sub> + pK<sub>Seitenkette</sub>)/3', ' '], ['(pK<sub>alpha-Amino</sub> + pK<sub>alpha-Carboxyl</sub>)/2', ' '], ['(pK<sub>alpha-Amino</sub> + pK<sub>alpha-Carboxyl</sub>)', ' '], 'A', 0, 'none' ]) ;
  load_question(['Wie berechnet man n&auml;herungsweise den pI von Cys?', ['(pK<sub>alpha-Carboxyl </sub>+ pK<sub>Seitenkette</sub>)/2', ' '], ['(pK<sub>alpha-Amino</sub>+ pK<sub>Seitenkette</sub>)/2', ' '], ['(pK<sub>alpha-Carboxyl </sub>+ pK<sub>alpha-Amino</sub> + pK<sub>Seitenkette</sub>)/3', ' '], ['(pK<sub>alpha-Amino</sub> + pK<sub>alpha-Carboxyl</sub>)/2', ' '], ['(pK<sub>alpha-Amino</sub> + pK<sub>alpha-Carboxyl</sub>)', ' '], 'A', 0, 'none' ]) ;
  load_question(['Die pK<sub>a</sub>-Werte von Lys sind 2.16, 9.06, 10.54. Welches ist sein pI?', ['5.61', ' '], ['6.35', ' '], ['9.80', ' '], ['7.25', ' '], ['keiner der obigen Werte trifft zu', ' '], 'C', 0, 'none' ]) ;
  load_question(['Welche Aminos&auml;ure tr&auml;gt am meisten zur Pufferwirkung von Proteinen im Zytoplasma bei?', ['Arg', 'nur die Seitenkette kann puffern, ihr pKa ist stark basisch'], ['Glu', ' nur die Seitenkette kann puffern, ihr pKa ist sauer'], ['Lys', 'nur die Seitenkette kann puffern, ihr pKa ist basisch'], ['His', 'nur die Seitenkette kann puffern, ihr pKa ist etwa 6.5'], ['Asp', 'nur die Seitenkette kann puffern, ihr pKa ist sauer'], 'D', 0, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber die Aminos&auml;urenzusammensetzung von Proteinen ist richtig?<br>1. In den meisten Proteinen kommt jede der 20 Aminos&auml;uren mit etwa 5% H&auml;ufigkeit vor.<br>2. Nur in wenigen Proteinen kommen gewisse Aminos&auml;uren, z.B. Cys, sehr h&auml;ufig vor.<br>3. Das Verh&auml;ltnis der basischen zu den sauren Aminos&auml;uren ist stets etwa 1:1.<br>4. Das Verh&auml;ltnis der polaren zu den unpolaren Aminso&auml;uren kann stark variieren.', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'none' ]) ;
  load_question(['Welche Aminos&auml;ure hat keine aromatische Seitenkette?<br>1. Val<br>2. Pro<br>3. Asn<br>4. Trp', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Welche Aminos&auml;ure hat zwei chirale C-Atome?<br>1. Pro<br>2. Thr<br>3. Trp<br>4. Ile', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'none' ]) ;
  load_question(['Welches Protein ist fibrill&auml;r?<br>1. Kollagen<br>2. Keratin<br>3. Elastin<br>4. Histon', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' Histone sind globuläre Proteine'], ['1, 2, 3 und 4 treffen zu', ' Histone sind globuläre Proteine'], 'A', 1, 'none' ]) ;
  load_question(['Welche Aminos&auml;ure absorbiert Licht mit einer Wellenl&auml;nge von 280 nm?<br>1. Trp<br>2. Cys<br>3. Tyr<br>4. Val', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Aus welcher Information kann man die genaue dreidimensionale Struktur eines Proteins herleiten?<br>1. Aminos&auml;urensequenz und Aminos&auml;urenzusammensetzung<br>2. Beugung von R&ouml;ntgenstrahlen am Proteinkristall<br>3. Absorptionsspektren der Proteinl&ouml;sung<br>4. NMR-Spektren der Proteinl&ouml;sung', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber prosthetische Gruppen von Proteinen ist richtig?<br>1. Sie leiten sich oft von Vitaminen ab.<br>2. Sie sind stets kovalent an ein Protein gebunden.<br>3. Sie ver&auml;ndern das Absorptionsspektrum eines Proteins.<br>4. Sie enthalten stets ein Metallatom.', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' prosthetische Gruppen sind nicht immer kovalent ans Protein gebunden'], ['4 trifft zu', ' Metalle zählt man nicht zu den prosthetischen Gruppen, welche als kleine, organische Moleküle definiert sind'], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['Welches Protein geh&ouml;rt zur Klasse der zusammengesetzten Proteine?<br>1. H&auml;moglobin<br>2. Cytochrom c<br>3. Ferritin<br>4. beta-Lipoprotein', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Phosphors&auml;ure hat die pK<sub>a</sub>-Werte 2.15, 6.82 und 12.38. Welche Aussage ist richtig?<br>1. Phoshors&auml;ure puffert im Bereich pH 2 bis pH 2.3 sehr gut.<br>2. Bei pH 6.82 ist [ H<sub>2</sub>PO<sub>4</sub><sup>- </sup>] = [ HPO<sub>4</sub><sup>2-</sup>]<br>3. Bei pH 1 ist [ H<sub>3</sub>PO<sub>4</sub> ] &gt; [ H<sub>2</sub>PO<sub>4</sub><sup>-</sup>]<br>4. Bei pH 9.6 ist [ HPO<sub>4</sub><sup>2- </sup>] die vorherrschende Form', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber die Titrationskurve von Gly ist <span class="fett">falsch</span>?<br>1. Beim zweiten pK<sub>a</sub> sind die Konzentrationen der ungeladenen und der einfach negativ geladenen Molek&uuml;le gleich gross.<br>2. Bei pH 1 tragen fast alle Molek&uuml;le eine negative Ladung.<br>3. Der pI entspricht dem Durschschnitt der beiden pK<sub>a</sub> Werte.<br>4. Der erste pK<sub>a</sub> ist gleich dem pH, an dem die meisten Molek&uuml;le keine Nettoladung tragen.', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'none' ]) ;
  load_question(['Bei welchem pH ist dieses Peptid ein guter Puffer?<br>Acetyl-Ser-Ile-Gln-Asp-Asp-Thr-Gln-Val-Ile-Ser-His-Ala-Gly-His-Ser-Thr-Leu-His-Gly<br><br>1. pH 1<br>2. pH 4<br>3. pH 9<br>4. pH 6', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'C', 1, 'none' ]) ;
  load_question(['Die Seitenkette welcher Aminos&auml;ure kann eine H-Br&uuml;cke mit einem anderen Molek&uuml;l eingehen?<br>1. His<br>2. Gln<br>3. Lys<br>4. Ile', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Wie heisst die einzige Aminos&auml;ure, die kein chirales C-Atom besitzt?', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Glycin', 'Gly'], 4, 'none' ]) ;
  load_question(['Wie heisst die einzige Aminos&auml;ure, die eine sekund&auml;re Aminogruppe besitzt?', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Prolin', 'Pro'], 4, 'none' ]) ;
  load_question(['Wie heisst diejenige Aminos&auml;ure, welche die freie Drehbarkeit der Peptidbindung am meisten einschr&auml;nkt?', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Prolin', 'Pro'], 4, 'none' ]) ;
  load_question(['Das Insulin des Menschen und dasjenige der Ente unterscheiden sich in 6 Aminos&auml;urepositionen. Die Mutationen sind<br>(Mensch/Ente): Thr/Glu, Ser/Asn, Ile/Pro, Phe/Ala, Val/Ala, Thr/Ser.<br>Welches Insulin hat den niedrigeren pI? (Mensch oder Ente eintippen)', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Ente'], 4, 'none' ]) ;
  load_question(['Ammoniak hat einen pK<sub>a</sub> von 9.25. Bei welchem pH ist Ammoniak ein besserer Puffer gegen S&auml;ure: pH 8.25 oder pH 10.25? (Zahl eintippen)', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['10.25'], 4, 'none' ]) ;
  load_question(['Welche der Aminos&auml;uren Asp, His, Val, Thr, Arg, Gly ist am wenigsten polar?', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Valin', 'Val'], 4, 'none' ]) ;
  load_question(['Welche der Aminos&auml;uren Asn, His, Val, Thr, Arg, Glu ist am st&auml;rksten basisch?', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Arginin', 'Arg'], 4, 'none' ]) ;
  load_question(['Welche der Aminos&auml;uren Asn, Leu, Asp, Gln, Ser, Lys ist am st&auml;rksten sauer?', [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], [' ', ' '], ['Asparaginsäure', 'Asp'], 4, 'none' ]) ;
  load_question(['Welche Aminos&auml;ure wurde hier posttranslationell mit einem Zucker modifiziert? ', ['Asp', ' '], ['Asn', ' '], ['Glu', ' '], ['Gln', ' '], ['Lys', ' '], 'B', 0, 'testbilder/Asn-Zuck.gif' ]) ;
  load_question([' Welche andere Aminos&auml;ureseitenkette ausser der gezeigten kann auch O-glykosidische Bindungen machen?<br><br>1. Glu<br>2. Val<br>3. Asn<br>4. Thr ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'D', 1, 'testbilder/Ser-Zuck.gif' ]) ;
  load_question(['(a) Die Formel zeigt eine posttranslationelle Modifikation von Phenylalanin <br><br>weil<br><br>(b) es kein Codewort f&uuml;r Phospho-Phenylalanin gibt. ', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'testbilder/Tyr-P.gif' ]) ;
  
}