// Fragen Editor 1.1

function get_questions() {

  load_question(['a) In einer <img src="testbilder/beta.gif">-Schleife kommt die Aminosäure Gly besonders selten vor<br><br>weil<br><br>b) Gly die Drehbarkeit der Peptidkette stark einschränkt.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'E', 2, 'none' ]) ;
  load_question(['a) In natürlichen Proteinen kommen ausschliesslich L-Aminosäuren vor<br><br>weil<br><br>b) D-Aminosäuren keine Sekundärstrukturen ausbilden können.', ['a und b richtig; b als Begründung von a richtig', ' D-Aminosäuren können Sekundärstrukturen ausbilden, sie werden in der Natur aber nicht in Proteine eingebaut'], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'C', 2, 'none' ]) ;
  load_question(['a) Van der Waals Bindungen zwischen den Seitenketten im Proteininnern stabilisieren die Tertiärstruktur<br><br>weil<br><br>b) die polaren Seitenketten bevorzugt an der Oberfläche des Proteins liegen.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) In einem globulären Protein kommen alle Aminosäuren in a-Helices, ß-Faltblättern oder &beta-Schleifen vor<br><br>weil<br><br>b) diese Strukturen die Anzahl der H-Brücken zwischen den Peptidbindungen optimieren.', ['a und b richtig; b als Begründung von a richtig', 'Nicht alle AS eines Proteins sind Bestandteil von Sekundärstrukturen.'], ['a und b richtig; b als Begründung von a falsch', ' nicht alle AS eines Proteins sind Bestandteil von Sekundärstrukturen'], ['a richtig, b falsch', 'Nicht alle AS eines Proteins sind Bestandteil von Sekundärstrukturen.'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Die Kontaktflächen zwischen den Untereinheiten von Hämoglobin sind komplementär zueinander<br><br>weil<br><br>b) der hydrophobe Effekt den grössten Energiebeitrag für den Zusammenhalt der Untereinheiten liefert.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) Bei der Denaturierung bleiben die Sekundärstrukturelemente eines Proteins grossenteils erhalten<br><br>weil<br><br>b) diese durch sehr viele H-Bindungen stablisiert werden.', ['a und b richtig; b als Begründung von a richtig', ' Denaturierung lässt nur die Primärstruktur intakt'], ['a und b richtig; b als Begründung von a falsch', 'Denaturierung lässt nur die Primärstruktur intakt.'], ['a richtig, b falsch', 'Denaturierung lässt nur die Primärstruktur intakt.'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Als chemische Evolution bezeichnet man die Veränderung der Aminosäurensequenz verwandter Proteine aus verschiedenen Spezies<br><br>weil<br><br>b) die Sequenzunterschiede mit zunehmender evolutionärer Distanz zunehmen.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'A', 2, 'none' ]) ;
  load_question(['Das antiparallele ß-Faltblatt auf der Abbildung besteht aus 6 Strängen, jeder Strang hat 7 Aminosäuren. Hydrophobe Seitenketten sind gelb, hydrophile rot, das Peptidrückgrat grün und die ß-Schleifen grau. Welcher Sequenzausschnitt entspricht am ehesten dieser Struktur? y = eine hydrophobe Aminosäure, w = eine hydrophile Aminosäure, t = eine Aminosäure in einer ß-Schleife.', ['....y-y-y-y-w-w-w-t-t-t-t-y-y-y-y-w-w-w-t-t-t-t....', 'Reste, die in der Sequenz benachbart sind, schauen nach oben und nach unten; die Sequenz muss deshalb y-w-y-w... oder w-y-w-y... enthalten'], ['....y-w-y-w-y-w-y-t-t-t-t-y-w-y-w-y-w-y-t-t-t-t....', ' fast richtig, aber es sind je 3 hydrophobe und 4 hydrophile Reste pro Strang, daher muss die Sequenz w-y-w-y-w-y-w lauten; D ist korrekt'], [' ....y-y-w-w-y-y-w-t-t-t-t-y-y-w-w-y-y-w-t-t-t-t....', ' Reste, die in der Sequenz benachbart sind, schauen nach oben und nach unten; die Sequenz muss deshalb y-w-y-w... oder w-y-w-y... enthalten'], ['....w-y-w-y-w-y-w-t-t-t-t-w-y-w-y-w-y-w-t-t-t-t....', ' '], ['....w-w-w-w-w-w-w-t-t-t-t-y-y-y-y-y-y-y-t-t-t-t...', ' Reste, die in der Sequenz benachbart sind, schauen nach oben und nach unten; die Sequenz muss deshalb y-w-y-w... oder w-y-w-y... enthalten'], 'D', 0, 'testbilder/030201.jpg' ]) ;
  load_question(['Welcher Wert entspricht am ehesten der Fläche des in der Abbildung grün gezeichneten 6-strängigen ß-Faltblatts mit je 7 Aminosäuren pro Strang?', ['100 (Angstrom)<sup>2</sup>', ' Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['500 (Angstrom)<sup>2</sup>', ' Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['1000 (Angstrom)<sup>2</sup>', ' Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['2000 (Angstrom)<sup>2</sup>', 'Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['5000 (Angstrom)<sup>2</sup>', 'Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], 'B', 0, 'testbilder/030201.jpg' ]) ;
  load_question(['Welche Aussage über diese Struktur ist <span class="fett">falsch</span>?', ['Es ist ein antiparalleles Faltblatt.', ' '], ['Der Abstand zwischen den Peptidketten beträgt etwa 4.7 Angstrom.', ' '], ['Die Seitenketten liegen über und unter der Ebenen der Peptidbindungen.', ' '], ['Die Peptidbindungen liegen alle in derselben Ebene senkrecht zur Richtung der Peptidkette.', ' Die Ebenen der Peptidbindungen wechseln, daher der Name "Faltblatt" '], ['Es handelt sich um eine Struktur aus lauter L-Aminosäuren.', ' '], 'D', 0, 'testbilder/030202.gif' ]) ;
  load_question(['Welche Aussage über Proteindomänen ist <span class="fett">falsch</span>?', ['Sie enthalten oft 10-20 Aminosäuren.', ' Domänen sind grösser, typisch sind 100-150 Aminosäuren'], ['Sie sind oft strukturell unabhängig.', ' '], ['Sie haben oft eine spezialisierte Funktion.', ' '], ['Sie ähneln oft einem kleinen globulären Protein.', ' '], ['Sie werden oft auf der DNA durch ein einzelnes Exon kodiert.', ' '], 'A', 0, 'none' ]) ;
  load_question(['Wieviele H-Bindung mit anderen Aminosäuren macht die 10. Aminosäure in einer a-Helix aus 12 Aminosäuren?', ['0', ' Die 10. AS kann noch eine H-Bindung machen, denn diese liegen zwischen AS i und i+4'], ['1', ' Die H-Bindungen liegen zwischen der AS i und i+4, daher kann die 10. AS nur noch eine H-Bindung machen'], ['2', ' Die H-Bindungen liegen zwischen der AS i und i+4, daher kann die 10. AS nur noch eine H-Bindung machen'], ['3', ' Eine AS in einer alpha-Helix kann höchstens zwei H-Bindung machen'], ['4', ' Eine AS in einer alpha-Helix kann höchstens zwei H-Bindung machen'], 'B', 0, 'none' ]) ;
  load_question(['Welche Aminosäure einer a-Helix macht eine H-Brücke mit der 2. Aminosäure?', ['1. Aminosäure', ' die H-Bindung liegen zwischen AS i und i+4 '], ['3. Aminosäure', 'Die H-Bindung liegen zwischen AS i und i+4.'], ['4. Aminosäure', 'Die H-Bindung liegen zwischen AS i und i+4.'], ['5. Aminosäure', 'Die H-Bindung liegen zwischen AS i und i+4.'], ['6. Aminosäure', 'Die H-Bindung liegen zwischen AS i und i+4.'], 'E', 0, 'none' ]) ;
  load_question(['Wieviele verschiedene Disulfidbrücken können in einer Polypeptidkette mit 6 Cysteinresten entstehen?', ['6', ' 5 x 3 x 1 Möglichkeiten'], ['12', ' 5 x 3 x 1 Möglichkeiten'], ['15', ' 5 x 3 x 1 Möglichkeiten'], ['21', ' 5 x 3 x 1 Möglichkeiten'], ['36', '5 x 3 x 1 Möglichkeiten '], 'C', 0, 'none' ]) ;
  load_question(['Welche Aussage über Konformationsänderungen ist <span class="fett">falsch</span>?', ['Konformationänderungen werden durch die Bindung von Substraten an Enzyme ausgelöst', ' '], ['Konformationsänderungen sind charakterisiert durch die Spaltung und Neubildung von nicht-kovalenten Bindungen', ' '], ['Konformationsänderungen sind reversibel', ' '], ['Der Energiegehalt der verschiedenen Konformationen eines Proteins ist ähnlich', ' '], ['Bei Konformationsänderungen ändert die Sekundärstruktur nicht', 'Nur die Primärstruktur ändert bei einer Konformationsänderung nicht'], 'E', 0, 'none' ]) ;
  load_question(['Unter welchen Bedingungen wird ein Protein in der Regel NICHT denaturiert?', ['pH 1', ' '], ['8 M Harnstoff', ' '], ['6 M Guanidiniumhydrochlorid ', ' '], ['2 M Kochsalz', ' Kochsalz kann zwar die Konformation eines Proteins beeinflussen, aber es wird in der Regel durch Salz nicht denaturiert'], ['100 °C', ' '], 'D', 0, 'none' ]) ;
  load_question(['Die gezeigte Helix aus 13 Resten hat eine polare (violett) und eine apolare (grau) Seite. Welche Sequenz entspricht am ehesten dieser Helix? w = polare Aminosäure, y = apolare Aminosäure.', ['w-w-w-w-w-w-w-y-y-y-y-y-y', ' 3.6 AS pro Umdrehung: Es können also höchstens 1-2 AS auf der gleichen Seite der Helix liegen'], ['w-w-y-y-w-w-y-y-w-w-y-y-w', ' 3.6 AS pro Umdrehung: Es können also nicht immer zwei AS auf der gleichen Seite der Helix liegen'], ['w-w-w-y-y-y-w-w-w-y-y-y-w', ' 3.6 AS pro Umdrehung: Es können also höchstens 1-2 AS auf der gleichen Seite der Helix liegen'], ['w-y-w-y-w-y-w-y-w-y-w-y-w', ' 3.6 AS pro Umdrehung: Nicht jede zweite AS kann auf der gleichen Seite der Helix liegen'], ['y-w-w-y-y-w-w-y-w-w-y-y-w', ' '], 'E', 0, 'testbilder/030203.jpg' ]) ;
  load_question(['Welches Merkmal der Quartärstruktur ist falsch? ', ['Die Kontaktflächen zwischen den Untereinheiten zeigen eine räumlich komplementäre Struktur', ' '], ['Hydrophobe Wechselwirkungen stabilisieren den Zusammenhalt der Untereinheiten', ' '], ['H-Bindungen stabilisieren den Zusammenhalt der Untereinheiten', ' '], ['Die Quartärstrukturen entsteht spontan durch Selbstorganisation', ' '], ['Zur Bildung der Quartästruktur braucht es Untereinheiten mit verschiedenen Sequenzen', ' '], 'E', 0, 'none' ]) ;
  load_question(['Welche Beobachtung zeigt, dass die Information für die native Proteinstruktur in der Aminosäurensequenz enthalten ist?', ['Verdauung des nativen Proteins mit einer Protease zerstört seine biologische Aktivität ', ' '], ['Kochen des Proteins zerstört seine biologische Aktivität', ' '], ['Dialyse des nativen Proteins gegen Puffer von pH 7 zerstört seine biologische Aktivität', ' '], ['Dialyse des denaturierten Proteins gegen Puffer von pH 7 bringt seine biologische Aktivität zurück', ' '], ['Dialyse des denaturierten Proteins gegen 8 M Harnstofflösung bringt seine biologische Aktivität zurück', ' '], 'D', 0, 'none' ]) ;
  load_question(['Was erklärt die Verklumpung von Hämoglobin S (Sichelzellanämie), die man bei Hämoglobin A (normales Hämoglobin des Erwachsenen) nicht beobachtet? ', ['HbS enthält mehr hydrophobe Aminosäuren als HbA', ' '], ['HbS enthält mehr hydrophile Aminosäuren als HbA', ' '], ['In einer einzigen Position enthält HbS ein Glu anstelle eines Val', ' '], ['In einer einzigen Position enthält HbS ein Val anstelle eines Glu', ' '], ['HbS bindet Sauerstoff schlechter als HbA', ' '], 'D', 0, 'none' ]) ;
  load_question(['<p>Welche Eigenschaft einer Polypeptidkette ist für die Ausbildung von Sekundärstruktur hauptverantwortlich?</p><p>1. Freie Drehbarkeit der Peptidbindung<br>2. H-Brücken zwischen Seitenketten<br>3. Beweglichkeit der Seitenketten<br>4. H-Brücken zwischen Peptidbindungen</p>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'D', 1, 'none' ]) ;
  load_question(['<p>Welche Bindung ist frei drehbar?</p><p>1. Bindung 1<br>2. Bindung 2<br>3. Bindung 3<br>4. Bindung 4</p>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'testbilder/030204.gif' ]) ;
  load_question(['<p>Welche Aussage über Disulfidbrücken ist richtig?</p><p>1. Sie können Peptidketten miteinander verknüpfen<br>2. Sie stabilisieren vor allem intrazelluläre Proteine<br>3. Sie können innerhalb einer Peptidkette liegen<br>4. Sie werden durch Oxidationsmittel gespalten.</p>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['<p>Welche Aussage über die a-Helix ist richtig?</p><p>1. Zwei H-Bindungen pro Peptidbindung<br>2. Seitenketten gegen aussen gerichtet<br>3. Ebenen der Peptidbindung parallel zur Helixachse<br>4. H-Bindung zwischen Aminosäuren i und i+4.</p>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'E', 1, 'none' ]) ;
  load_question(['<p>Welche Aussage über das <img src="testbilder/beta.gif">-Faltblatt ist richtig?</p><p>1. zwei H-Bindungen pro Peptidbindung<br>2. Seitenketten abwechselnd nach oben und unten gerichtet<br>3. H-Bindungen senkrecht zur Richtung der Peptidketten<br>4. H-Bindung zwischen Aminosäuren i und i+3.</p>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['<p>Welche Aussage über die prosthetische Hämgruppe von Myoglobin ist <span class="fett">falsch</span>?</p><p>1. Sie ist kovalent mit der Peptidkette verknüpft.<br>2. Sie liegt an der Oberfläche des Moleküls.<br>3. Sie ist vorwiegend von polaren Aminosäureseitenketten umgeben.<br>4. Sie enthält im Zentrum ein Eisen.</p>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['<p>Welche Aminosäureseitenketten können im Proteininnern nur über van der Waals-Bindungen miteinander interagieren?</p><p>1. Val-Ser<br>2. Val-Leu<br>3. Ile-Thr<br>4. Gln-Ser</p>', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' auch im Innern kann sich eine H-Bindung zwischen den Seitenketten von Gln und Ser ausbilden '], ['1, 2, 3 und 4 treffen zu', ' auch im Innern kann sich eine H-Bindung zwischen den Seitenketten von Gln und Ser ausbilden '], 'A', 1, 'none' ]) ;
  load_question(['<p>Welche Aussage über Denaturierung ist <span class="fett">falsch</span>?</p><p>1. Denaturierung ist immer reversibel<br>2. Denaturierung zerstört die Primärstruktur nie<br>3. Bei der Denaturierung fällt das Protein immer aus<br>4. Denaturierung zerstört stets die biologische Aktivität des Proteins</p>', ['1, 2, und 3 treffen zu', ''], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question([' Welche Aussage über das gezeigte Protein ist richtig?<br><br>1. Es enthält alpha-Helix und beta-Faltblatt<br>2. Es enthält keine beta-Schleifen<br>3. Es ist aus verschiedenen Domänen aufgebaut<br>4. Es ist etwa 50 Aminosäuren lang.', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'B', 1, 'testbilder/domainstructure.gif' ]) ;
  load_question([' Welche Aussage über die Flexibilität von Proteinen ist richtig?<br><br>1. sie ermöglicht unterschiedliche Konformationen eines Proteins<br>2. sie ist dafür verantwortlich, dass die meisten Proteine zwischen 50 und 100 °C denaturieren <br>3. sie trägt zur Spezifität der Enzyme bei<br>4. sie ist in der Kristallstruktur eines Proteins nicht sichtbar', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'E', 1, 'none' ]) ;
  load_question([' Unter welchen Bedingungen wird ein Protein denaturiert?<br><br>1. kochen bei pH 7<br>2. kochen bei pH 3<br>3. mit einer konzentrierten Lösung des Moleküls A behandeln <br>4. mit einer konzentrierten Lösung des Moleküls B behandeln ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'E', 1, 'testbilder/urea+gdmcl.gif' ]) ;
  load_question([' Weshalb sind die Strukturen von Myoglobin (blau) und der alpha-Untereinheit von Hämoglobin (gelb) sehr ähnlich? <br><br>1. weil die beiden Proteine ähnliche Sequenzen haben <br>2. weil die beiden Proteine unter identischen Bedingungen kristallisiert worden sind <br>3. weil die beiden Proteine in der Evolution aus einem gemeinsamen Vorläuferprotein entstanden sind <br>4. weil die prosthetische Hämgruppe ähnliche Strukturen erzeugt. ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'B', 1, 'testbilder/Hb+Mb.gif' ]) ;
  load_question(['Welche Zuordnungen sind richtig?<br><br>A Lineare Abfolge der Aminosäuren<br>B Räumliche Gesamtstruktur einer Polypeptidkette<br>C Abschnitte mit regelmässiger Faltung<br>D Assoziation von mehreren Polypeptidketten<br>E Kovalente Verknüpfung von Polypeptidketten über Aminosäureseitenketten', ['Disulfidbrücke', ' '], ['Primärstruktur', ' '], ['Sekundärstruktur', ' '], ['Tertiärstruktur', ' '], ['Quartärstruktur', ' '], ['E', 'A', 'C', 'B', 'D'], 3, 'none' ]) ;
  load_question([' Welche Aussage zu dieser Struktur trifft zu?<br><br>1. sie enthält ein antiparalleles Faltblatt<br>2. Stränge des Faltblatts sind mit einer alpha-Helix verknüpft <br>3. Stränge des Faltblatts sind mit beta-Schleifen verbunden<br>4. in der Primärstruktur liegt die alpha-Helix direkt vor dem C-Term', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'A', 1, 'testbilder/sheet5.gif' ]) ;
  load_question(['Welche Zuordnung passt am besten?<br><br>A hydrophober Effekt<br>B Kontaktfläche zwischen den Untereinheiten eines oligomeren Proteins<br>C ionische Bindung<br>D Proteindomäne<br>E <img src="testbilder/alpha.gif">-Helix', ['räumliche Komplementarität', ' '], ['Seitenketten von Asp und Arg', ' '], ['Tendenz von Aminosäuren, den Kontakt mit Wasser zu meiden', ' '], ['Myoglobin', ' '], ['Exon auf der DNA', ' '], ['B', 'C', 'A', 'E', 'D'], 3, 'none' ]) ;
  load_question(['Welche Zuordnung ist richtig?<br><br>A <img src="testbilder/beta.gif">-Faltblatt<br>B Coiled Coil<br>C <img src="testbilder/beta.gif">-Schleife<br>D Kollagenhelix<br>E Keratin', ['Faserprotein mit einer Tripelhelix als Grundstruktur', ' '], ['Faserprotein mit vielen Disulfidbrücken', ' '], ['zwei umeinander gewundene <img src="testbilder/alpha.gif">-Helices', ' '], ['H-Brücke zwischen der 1. und der 4. Aminosäure', ' '], ['regelmässige Struktur mit H-Brücken zwischen fast gestreckten Peptidketten', ' '], ['D', 'E', 'B', 'C', 'A'], 3, 'none' ]) ;
  load_question(['Welche Zuordnung ist richtig?<br><br>A Chaperone<br>B Proteasom<br>C Denaturierung<br>D Reduktion von Disulfidbrücken<br>E endoplasmatisches Retikulum', ['HO-CH<sub>3</sub>-CH<sub>2</sub>-SH', ' '], ['NH<sub>2</sub>-CO-NH<sub>2</sub>', ' '], ['Proteolyse', ' '], ['Proteinaggregate', ' '], ['Proteinsynthese', ' '], ['D', 'C', 'B', 'A', 'E'], 3, 'none' ]) ;
  load_question(['Welche Zuordung trifft zu?<br><br>A Sichelzellanämie<br>B Chaperone<br>C Serinproteasen<br>D Histone<br>E Plasmodium falciparum', ['Proteinfaltung', ' '], ['Bindung an DNA', ' '], ['basiche Proteine', ' '], ['molekulare Krankheit', ' '], ['Malaria', ' '], ['B', 'D', 'D', 'A', 'E'], 3, 'none' ]) ;
  load_question(['Welche Arten von Bindungen und Wechselwirkungen sind mit den Buchstaben A bis E gekennzeichnet??', ['hydrophobe Wechselwirkungen', ' '], ['elektrostatische Anziehung', ' '], ['Disulfidbrücke', ' '], ['kovalente Bindung', ' '], ['H-Bindungen', ' '], ['B', 'E', 'A', 'C', 'D'], 3, 'testbilder/SK-Wechselwirk.gif' ]) ;
  
}