// Fragen Editor 1.1
   
 

 

function get_questions() {

  load_question(['Welche Verbindung kommt in Proteoglykanen <span class="fett">nicht</span> vor?', ['Heparin', ' '], ['Chondroitinsulfat', ' '], ['Hyaluronsäure', ' '], ['Core Peptid', ' '], ['Glykolipid', ' '], 'E', 0, 'none' ]) ;
  load_question(['Mit der Seitenkette welcher Aminosäure sind Zucker kovalent verbunden?', ['Asp', ' '], ['Asn', ' '], ['Glu', ' '], ['Gln', ' '], ['Cys', ' '], 'B', 0, 'none' ]) ;
  load_question(['Wie heisst dieses Heteroglykan?', ['Dextran', ' '], ['Inulin', ' '], ['Hyaluronsäure', ' '], ['Polysaccharose', ' '], ['Chondroitinsulfat', ' '], 'C', 0, 'testbilder/050101.gif' ]) ;
  load_question(['Wie gross ist die Energiereserve, die der Mensch in Form von Blutglucose besitzt; gemessen in Prozent des Tagesbedarfs von 10’000 kJ? (Blutvolumen = 5 l, [Glucose] = 5 mM, Energiegehalt = 20 kJ/g Glucose)', ['1%', ' '], ['5%', ' '], ['10%', ' '], ['15%', ' '], ['25%', ' '], 'A', 0, 'none' ]) ;
  load_question(['Welche Aussage über den Zuckerteil von Glykoproteinen ist <span class="fett">falsch</span>?', ['er beeinflusst die Konformation des Proteinteils', ' '], ['er ist kovalent an das Protein gebunden', ' '], ['er ist bei allen Glykoproteinen sehr ähnlich', ' '], ['er enthält Zuckerderivate', ' '], ['er wird posttranslationell gebildet', ' '], 'C', 0, 'none' ]) ;
  load_question(['Welches der folgenden Polysaccharide ist <span class="fett">kein</span> Polymer der Glucose?', ['Amylopektin', ' '], ['Amylose', ' '], ['Glycogen', ' '], ['Murein', ' '], ['Glycogen', ' '], 'D', 0, 'none' ]) ;
  load_question(['Wie heisst dieses Homoglykan?', ['Stärke', ' Stärke enthält alpha-glykosidisch verknüpfte Glucosereste'], ['Glykogen', ' Glykogen enthält alpha-glykosidisch verknüpfte Glucosereste'], ['Saccharose', ' Inulin ist Polyfructose'], ['Lactose', ' Chitin ist ein Polymer von N-Acetylglucosamin'], ['Cellulose', ' '], 'E', 0, 'testbilder/050102.gif' ]) ;
  load_question(['Welche Aussage über Glykoproteine trifft zu?<br><br>1. Zucker und Protein sind über elektrostatische Kräfte aneinander gebunden<br>2. sie enthalten viele repetitive Disaccharideinheiten<br>3. sie binden viel Wasser<br>4. sie kommen vorwiegend extrazellulär vor', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'D', 1, 'none' ]) ;
  load_question(['Welche Aussage ist richtig?<br><br>1. Der Zuckeranteil ist bei Glykoproteinen geringer als bei Proteoglykanen<br>2. Amylose ist ein unverzweigtes Homoglykan<br>3. Inulin passiert die Glomerulusmembran ungehindert<br>4. Cellulose ist eine wichtige Energiequelle bei vegetarischer Ernährung', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'A', 1, 'none' ]) ;
  load_question(['Welche der folgenden Verbindungen ist ein Polysaccharid?<br><br>1. Hyaluronsäure<br>2. <img src="testbilder/beta.gif">-Carotin<br>3. Heparin<br>4. Keratin', ['1, 2, und 3 treffen zu', ' '], ['1 und 3 treffen zu', ' '], ['2 und 4 treffen zu', ' '], ['4 trifft zu', ' '], ['1, 2, 3 und 4 treffen zu', ' '], 'B', 1, 'none' ]) ;
  load_question(['a) Der Energiegehalt von Salat ist für den Menschen niedrig,<br><br>weil<br><br>b) der Mensch keine <img src="testbilder/alpha.gif">-Glucosidase besitzt.', ['a und b richtig; b als Begründung von a richtig', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a und b richtig; b als Begründung von a falsch', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a richtig, b falsch', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a falsch, b richtig', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], ['a falsch, b falsch', ' Um Cellulose zu verdauen, ist eine beta-Glucosidase nötig, die dem Menschen fehlt'], 'C', 2, 'none' ]) ;
  load_question(['a) Penicillin behindert den Aufbau von Peptidoglykanen in der Bakterienzellwand,<br><br>weil<br><br>b) es ein Enzym hemmt, das die Quervernetzung der Peptide katalysiert.', ['a und b richtig; b als Begründung von a richtig', ' '], ['a und b richtig; b als Begründung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'A', 2, 'none' ]) ;
  load_question(['a) Lysozym hemmt die Bildung der Bakterienwand,<br><br>weil<br><br>b) es eine Peptidbindung in Murein spaltet.', ['a und b richtig; b als Begründung von a richtig', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a und b richtig; b als Begründung von a falsch', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a richtig, b falsch', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a falsch, b richtig', ' Lysozym spaltet glykosidische Bindungen im Murein '], ['a falsch, b falsch', ' Lysozym spaltet glykosidische Bindungen im Murein '], 'E', 2, 'none' ]) ;
  load_question(['Zuordnung:<br><br>A Knorpel<br>B Cellulose<br>C Amylose<br>D Bakterienzellwand<br>E Milchzucker', ['Lactose', ' '], ['<img src="testbilder/alpha.gif">-1,4-glykosidische Bindung', ' '], ['<img src="testbilder/beta.gif">-1,4-glykosidische Bindung', ' '], ['Proteoglykane', ' '], ['Peptidoglykane', ' '], ['E', 'C', 'B', 'A', 'D'], 3, 'none' ]) ;
  load_question(['Zuordnung:<br><br>A Heteroglykan<br>B Glykoprotein<br>C Peptidoglykan<br>D Glykolipid<br>E Core Protein', ['Membranprotein', ' '], ['Hyaluronsäure', ' '], ['Hauptbestandteil der Bakterienzellwand', ' '], ['Membranlipid', ' '], ['Proteoglykan', ' '], ['B', 'A', 'C', 'D', 'E'], 3, 'none' ]) ;
  load_question(['Zuordnung:', ['N-glykosidische Bindung', ' '], ['<img src="testbilder/beta.gif">-1,3-glykosidische Bindung', ' '], ['<img src="testbilder/alpha.gif">-1,4-glykosidische Bindung', ' '], ['Peptidbindung', ' '], ['Amidbindung', ' '], ['D', 'A', 'B', 'E', 'C'], 3, 'testbilder/050103.gif' ]) ;
  load_question(['Welche Aussage über die mit einem Buchstaben bezeichnete Gruppe ist falsch?', ['alpha-1,6-glykosidische Bindung', ' '], ['alpha-1,4-glykosidische Bindung', ' '], ['nicht-reduzierendes Ende', ' '], ['reduzierendes Ende', ' '], ['C6-Atom von Glucose', ' '], 'D', 0, 'testbilder/glykogen-stryer.gif' ]) ;
  load_question([' Wo kommt das gezeigte Molekül vor?<br><br>1. in Stärke<br>2. in sauren Mucopolysacchariden<br>3. in Glykoproteinen<br>4.in Glycosaminoglykanen ', ['1, 2 und 3 sind richtig', ' '], ['1 und 3 sind richtig', ' '], ['2 und 4 sind richtig', ' '], ['4 ist richtig', ' '], ['alle sind richtig', ' '], 'C', 1, 'testbilder/heparin.jpg' ]) ;
  load_question(['Welche Aussage über das gezeigte Molekül ist richtig?', ['Es ist ein Proteoglykan', ' '], ['Es ist Glykolipid', ' '], ['Es ist ein Glykosaminoglykan ', ' '], ['Es ist ein saures Mucopolysaccharid', ' '], ['Keine der obigen Antworten ist richtig', ' '], 'B', 0, 'testbilder/abb0406.gif' ]) ;
  
}