// Fragen Editor 1.1

function get_questions() {

  load_question(['Welches ist der wichtigste Grund, weshalb die Komplexit&auml;t von Biomolek&uuml;len mit zunehmender Molek&uuml;lmasse steigt?', ['Das gr&ouml;ssere Molekulargewicht', ' Die Grösse des Molekulargwichts korreliert nicht mit der Komplexität eines Moleküls'], ['Die gr&ouml;ssere Anzahl der Bausteine', 'Die grössere Anzahl der Bausteine ist noch kein Grund für die grössere Komplexität'], ['Die gr&ouml;ssere Vielfalt der Bausteine', 'Die grössere Vielfalt ist noch kein Grund für die grössere Komplexität'], ['Die gr&ouml;ssere M&ouml;glichkeit, die Bausteine zu kombinieren', ' '], ['Keine der obigen Antworten ist richtig', ' '], 'D', 0, 'none' ]) ;
  load_question(['Welches Element ist nach heutigem Wissen kein lebensnotwendiges Spurenelement?', ['Zink', ' häufig in Enzymen'], ['Selen', ' zwar selten, aber als Aminosäurederivat vorkommend (Selenocystein)'], ['Silizium', ' Silizium wurde bis heute noch nie als lebensnotwendiges Element nachgewiesen, obschon es das zweithäufigste Element der Erde ist'], ['Mangan', ' kommt in einigen wenigen Enzymen vor'], ['Molybd&auml;n', ' kommt in einigen wenigen Enzymen vor'], 'C', 0, 'none' ]) ;
  load_question(['Projiziert man die molekularen Gr&oouml;ssenverh&auml;ltnisse auf uns vertraute Dimensionen, so erh&auml;lt man erstaunliche Resultate. Der Durchmesser eines Wassermolek&uuml;ls sei 1 cm anstatt 0.3 nm. Welche der folgenden Gr&ouml;ssen ist richtig?', ['typisches Proteinmolek&uuml;l = 20 cm', ' '], ['Mitochondrium = 30 m', ' '], ['Leberzelle = 300 m', ' '], ['erwachsener Mensch = 60’000 km', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['a) Wasser bildet den Hauptteil der Masse einer Zelle<br><br>weil<br><br>b) Wasser durch die Zellmembran durchtreten kann.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' a) und b) sind zwar richtig, das begründende "weil" macht aber keinen Sinn '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' Wasser kann die Lipiddoppelschicht passieren, zusätzlich geht Wasser durch das Membranprotein Aquaporin ins Zellinnere.'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['Ordne die Bausteine den Biomakromolek&uuml;len zu:<br><br>A Proteine<br>B Polysaccharide<br>C Lipide<br>D DNA<br>E RNA', ['einfache Zucker (Monosaccharide)', ' '], ['Fetts&auml;uren', ' '], ['Aminos&auml;uren', ' '], ['Desoxyribose', ' '], ['Ribose', ' '], ['B', 'C', 'A', 'D', 'E'], 3, 'none' ]) ;
  load_question(['Der Molek&uuml;lbegriff wird in der Biochemie grossz&uuml;gig interpretiert. Welche Aussage kann f&uuml;r ein Molek&uuml;l im biochemischen Sinn zutreffen?', ['Das Molek&uuml;l besteht ausschliesslich aus Atomen, die nicht &uuml;ber Atombindungen (= kovalente Bindungen) miteinander verkn&uuml;pft sind.', ' Moleküle, in denen keine Atombindungen vorkommen, gibt es nicht.'], ['Das Molek&uuml;l besteht ausschliesslich aus Atomen, die miteinander &uuml;ber Atombindungen (= kovalente Bindungen) verkn&uuml;pft sind.', ' Das ist die chemische Definition eines Moleküls.'], ['Atome werden durch Kr&auml;fte zusammengehalten, die in Molek&uuml;len der unbelebten Materie nicht vorkommen.', ' Für die belebte Natur und die tote Materie gelten die gleichen physikalischen und chemischen Gesetze!'], ['Die meisten Atome des Molek&uuml;ls werden durch Atombindungen (= kovalente Bindungen) zusammengehalten, einige aber auch durch nicht-kovalente Bindungen.', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'none' ]) ;
  load_question(['Welche Substanzen z&auml;hlt man zu den biologischen Makromolek&uuml;len?', ['Aminos&auml;uren ', ' Aminosäuren sind zwar Bausteine der Proteine, selbst aber keine Makromoleküle.'], ['Proteine ', ' auch Proteine sind Biomakromoleküle'], ['Vitamin C', ' Vitamin C ist ein kleines Molekül.'], ['St&auml;rke', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'none' ]) ;
  load_question(['Mit welchen Themen befasst sich die Molekulare Zellbiologie im ersten Studienjahr des Medizinstudiums? ', ['Mit der Bildung und Weitergabe von Information zwischen Zellen', ' '], ['Mit der Struktur von Biomakromolek&uuml;len', ' '], ['Mit dem Auf- und Abbau von zelleigenen Stoffen ', ' '], ['Mit der Gewinnung von Energie aus Licht', ' Auch die Energiegewinnung aus Licht ist ein hochinteressantes Problem der Molekularen Zellbiologie, das aber im Rahmen des Medizinstudiums nicht diskutiert werden kann. '], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Was bedeutet der Begriff "Pathogenese"?', ['Behandlung von Krankheiten mit Medikamenten', ' '], ['Entstehung von Krankheiten', ' '], ['Diagnose von Krankheiten', ' '], ['Behandlung von Krankheiten mit nicht-operativen Methoden', ' '], ['Entstehung von Krankheiten durch Umweltgifte', ' '], 'B', 0, 'none' ]) ;
  load_question(['Machen Sie die beste Zuordnung!<br><br>A Mengenm&auml;ssig wichtigster Bestandteil der Ern&auml;hrung f&uuml;r alle, die vern&uuml;nftig essen<br>B Informations&uuml;bertragung bei der Zellteilung<br>C Kalorienreichster Bestandteil der menschlichen Ern&auml;hrung<br>D Muss mit der Nahrung aufgenommen werden, weil vom K&ouml;rper nicht selbst hergestellt<br>E Salz der Essigs&auml;ure', ['DNA', ' '], ['Fette', ' '], ['Kohlenhydrate', ' '], ['Acetat', ' '], ['Mangan', ' '], ['B', 'C', 'A', 'E', 'D'], 3, 'none' ]) ;
  load_question(['Welche funktionelle Gruppe kann keine H-Br&uuml;cke mit Wasser ausbilden?', ['Aldehyd', ' Der Carbonylsauerstoff eines Aldehyds kann eine H-Brücke bilden'], ['Alkohol', ' Sowohl der Sauerstoff als auch der Wasserstoff einer alkoholischen OH-Gruppe können H-Brücken eingehen'], ['Carbons&auml;ure', ' Sowohl die ungeladene als auch die geladene Säuregruppe kann H-Brücken bilden'], ['Methylgruppe', 'Die H-Atome einer Methylgruppe sind zuwenig polarisiert, um eine H-Brücke zu bilden '], ['Aminogruppe', ' Sowohl die geladene als auch die ungeladene Aminogruppe kann H-Brücken bilden'], 'D', 0, 'none' ]) ;
  load_question(['Welche Aussage erkl&auml;rt am besten, weshalb unpolare Stoffe in Wasser schlecht l&ouml;slich sind?', ['Sie sind viel gr&ouml;sser als Wasser', ' Die meisten Moleküle sind grösser als Wasser; Grösse hat nichts mit Löslichkeit zu tun.'], ['Ihre Dichte ist kleiner als diejenige von Wasser', 'Auch polare Stoffe haben gelegentlich eine geringerer Dichte als Wasser, z. B. Alkohole.'], ['Sie ziehen sich gegenseitig an', ' Wasserlösliche, geladene Stoffe ziehen sich gegenseitig an; unpolare Stoffe tragen keine Ladungen.'], ['Sie k&ouml;nnen keine H-Bindungen mit sich selbst ausbilden', ' Es ist zwar richtig, dass unpolare Stoffe keine H-Brücken mit sich selbst ausbilden; die Aussage erklärt die schlechte Löslichkeit aber nicht.'], ['Sie k&ouml;nnen keine H-Bindungen mit Wasser ausbilden.', ' Korrekt, den gute Wasserlöslichkeit beruht auf der Ausbildung von H-Brücken zwischen Wasser und den gelösten Molekülen'], 'E', 0, 'none' ]) ;
  load_question(['Welche Reihenfolge entspricht von links nach rechts zunehmender Polarit&auml;t?', ['Wasser, Methanol, Ethanol, Diethylether, Hexan', ' '], ['Hexan, Diethylether, Ethanol, Methanol, Wasser', ' '], ['Ethanol, Diethylether, Hexan, Methanol, Wasser', ' '], ['Diethylether, Hexan, Ethanol, Methanol, Wasser', ' '], ['Hexan, Ethanol, Diethylether, Methanol, Wasser', ' '], 'B', 0, 'none' ]) ;
  load_question(['Welche Aussage ist richtig?', ['Wasser ist ein gutes L&ouml;sungsmittel sowohl f&uuml;r positive wie f&uuml;r negative Ionen.', ' '], ['Bei pH 10 ist [OH-] = 10-3 M.', ' '], ['Bei pH 3 ist [H+] = 10-3 M', ' '], ['Bei pH 7 bilden Seifen in einer w&auml;sserigen Umgebung Liposomen.', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welches ist keine H-Bindung?', ['<img src="testbilder/h-bond1.gif" align="right">', ' Die H-Atome einer Methylgruppe sind zuwenig polarisiert, um mit dem Carbonylsaustff eine H-Bindung einzugehen'], ['<img src="testbilder/h-bond2.gif" align="right">', ' '], ['<img src="testbilder/h-bond3.gif" align="right">', ' '], ['<img src="testbilder/h-bond4.gif" align="right">', ' '], ['<img src="testbilder/h-bond5.gif" align="right">', ' '], 'A', 0, 'none' ]) ;
  load_question(['Welche Substanz ist bei pH 7 polar aber ungeladen?', ['Glucose', ' '], ['Glycin (eine Aminos&auml;ure)', ' bei pH 7 sind Aminosäuren geladen'], ['Glycerin', ' '], ['Stearins&auml;ure (eine Fetts&auml;ure)', ' bei pH 7 sind Fettsäuren deprotoniert und deshalb geladen'], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage stimmt sowohl f&uuml;r Wasser bei 20 °C als auch f&uuml;r Eis bei -10 °C?', ['Die Molek&uuml;le bilden ein sich st&auml;ndig sehr schnell &auml;nderndes Netzwerk von H-Bindungen.', ' gilt nur bei 20 °C.'], ['Die Dichte betr&auml;gt 1.00 g/cm3.', ' gilt nur bei 4 °C.'], ['Die Konzentration von [H+] ist 10-14 M.', ' gilt nur bei pH 14.'], ['Jedes Wassermolek&uuml;l bildet in der Regel 4 H-Bindungen zu benachbarten Wassermolek&uuml;len.', ' Bei jeder Temperatur können 4 -H-Brücken von einem Molekül Wasser ausgehen.'], ['', ' '], ['0', '0', '0', '1'], 6, 'none' ]) ;
  load_question(['Welche Aussage erkl&auml;rt, weshalb Kochsalz in Wasser besser l&ouml;slich ist als in Ethylalkohol?', ['Wasser bildet um NaCl eine Hydrath&uuml;lle.', ' NaCl kommt in Wasser nicht als Molekül vor, sondern als vollständig dissoziiertes Salz.'], ['NaCl ist in Wasser vollst&auml;ndig dissoziiert.', ' '], ['NaCl bildet mit Wasser H-Bindungen', ' Na+ und Cl- bilden keine H-Brücken.'], ['Wasser hat die h&ouml;here Dielektrizit&auml;tskonstante als Ethylalkohol.', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'none' ]) ;
  load_question(['a) Wasser ist ein polares Molek&uuml;l<br><br>weil<br><br>b) das O-Atom gr&ouml;sser ist als die H-Atome.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Die Grösse des O sagt nichts aus über die Polarität'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) Biologische Makromolek&uuml;le sind flexibel<br><br>weil<br><br>b) ihre dreidimensionale Struktur von schwachen, nicht-kovalenten Wechselwirkungen bestimmt wird.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Die schwachen Wechselwirkungen sind ein charakteristisches Merkmal aller Biomakromoleküle'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' Dank der vielen schwachen Wechselwirkungen sind Biomakromoleküle flexibel'], ['a richtig, b falsch', ' Dank der vielen schwachen Wechselwirkungen sind Biomakromoleküle flexibel'], ['a falsch, b richtig', ' Biomakromoleküle sind flexibel dank ihrer vielen schwachen Wechselwirkungen'], ['a falsch, b falsch', ' Dank der vielen schwachen Wechselwirkungen sind Biomakromoleküle flexibel'], 'A', 2, 'none' ]) ;
  load_question(['a) Die meisten biologischen Makromolek&uuml;le sind in Wasser gut l&ouml;slich<br><br>weil<br><br>b) Wasser ein chemisch inertes Molek&uuml;l ist.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Wasser ist nicht inert, denn es bildet H-Brücken und nimmt an vielen chemischen Reaktionen teil.'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' Wasser ist nicht inert, denn es bildet H-Brücken und nimmt an vielen chemischen Reaktionen teil.'], ['a richtig, b falsch', ' Wasser ist nicht inert, denn es bildet H-Brücken und nimmt an vielen chemischen Reaktionen teil.'], ['a falsch, b richtig', ' Die meisten biologischen Moleküle sind wasserlöslich; Lebensprozesse finden in wässriger Lösung statt.'], ['a falsch, b falsch', ' Die meisten biologischen Moleküle sind wasserlöslich; Lebensprozesse finden in wässriger Lösung statt. Wasser ist nicht inert, denn es bildet H-Brücken und nimmt an vielen chemischen Reaktionen teil.'], 'C', 2, 'none' ]) ;
  load_question(['Die Seitenketten von apolaren (hydrophoben) Aminos&auml;uren liegen mehrheitlich im Innern eines Proteins (siehe Kapitel "Proteine"). Welche Aussage trifft zu?', ['Im Innern des Proteins kann leichter ein "Wasserk&auml;fig" um die apolaren Seitenketten entstehen.', ' '], ['Im Innern des Proteins bilden sich keine entropisch ung&uuml;nstigen "Wasserk&auml;fige" um die apolaren Seitenketten.', ' '], ['Im Innern des Proteins k&ouml;nnen die apolaren Seitenketten leichter H-Br&uuml;cken untereinander ausbilden.', ' '], ['Zwischen den apolaren Seitenketten im Innern des Proteins gibt es schwache Bindungskr&auml;fte (van der Waals-Bindungen).', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'none' ]) ;
  
}