// Fragen Editor 1.1
 

function get_questions() {

  load_question(['Die Abbildung zeigt den schematischen Bau eines Phospholipids.<br>Ordne die Buchstaben A bis E den Begriffen 1 bis 5 zu.', ['Carbons&auml;ureester', ' '], ['Fetts&auml;ure', ' '], ['Alkohol', ' '], ['Phosphat', ' '], ['Glycerin', ' '], ['E', 'C', 'A', 'B', 'D'], 3, 'testbilder/040108.gif' ]) ;
  load_question(['Zuordnung:<br><br>A Energiespeicher<br>B essentieller Nahrungsbestandteil<br>C Entenfedern<br>D unges&auml;ttigte Fetts&auml;ure<br>E Eicosanoid', ['&Ouml;ls&auml;ure', ' '], ['Triglycerid', ' '], ['Wachs', ' '], ['Prostaglandin', ' '], ['Vitamin A', ' '], ['D', 'A', 'C', 'E', 'B'], 3, 'none' ]) ;
  load_question(['Zuordnung:<br><br>A Glycerophosphatid<br>B Steroid<br>C Eicosanoid<br>D Glycolipid<br>E Sphingosinphosphatid', ['Lecithin', ' '], ['Cerebrosid', ' '], ['Sphingomyelin', ' '], ['Progesteron', ' '], ['Prostaglandin', ' '], ['A', 'D', 'E', 'B', 'C'], 3, 'none' ]) ;
  load_question(['a) Der menschliche Organismus kann nicht alle notwendigen Fetts&auml;uren synthetisieren,<br><br>weil<br><br>b) ein Teil der Membranenlipide unges&auml;ttigte Fetts&auml;uren enthalten.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) Nat&uuml;rlich vorkommende Fetts&auml;uren besitzen immer eine gerade Anzahl Kohlenstoffatome,<br><br>weil<br><br>b) sie aus C2-Einheiten aufgebaut werden.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' FS mit ungerader Anzahl C-Atomen kommen vor, sind aber seltener'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' FS mit ungerader Anzahl C-Atomen kommen vor, sind aber seltener'], ['a richtig, b falsch', ' FS mit ungerader Anzahl C-Atomen kommen vor, sind aber seltener'], ['a falsch, b richtig', ' FS mit ungerader Anzahl C-Atomen kommen vor, sind aber seltener'], ['a falsch, b falsch', ' FS mit ungerader Anzahl C-Atomen kommen vor, sind aber seltener'], 'D', 2, 'none' ]) ;
  load_question(['a) Cholesterin bildet Mizellen,<br><br>weil<br><br>b) Cholesterin eine amphiphile Substanz ist.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Die Polarität von Cholesterin ist sehr gering, es ist deshalb nicht genügend amphiphil, um Mizellen zu bilden'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' Die Polarität von Cholesterin ist sehr gering, es ist deshalb nicht genügend amphiphil, um Mizellen zu bilden'], ['a richtig, b falsch', ' Die Polarität von Cholesterin ist sehr gering, es ist deshalb nicht genügend amphiphil, um Mizellen zu bilden'], ['a falsch, b richtig', ' Die Polarität von Cholesterin ist sehr gering, es ist deshalb nicht genügend amphiphil, um Mizellen zu bilden'], ['a falsch, b falsch', ' Die Polarität von Cholesterin ist sehr gering, es ist deshalb nicht genügend amphiphil, um Mizellen zu bilden'], 'E', 2, 'none' ]) ;
  load_question(['Um welche Verbindungen handelt es sich?', ['Sphingosin und Sphingomyelin', ' oben Sphingosin, unten Ceramid'], ['Sphingosin und Ceramid ', ' oben Sphingosin, unten Ceramid'], ['Ceramid und Sphingomyelin', ' oben Sphingosin, unten Ceramid'], ['Cerebrosid und Gangliosid', ' oben Sphingosin, unten Ceramid'], ['Cerebrosid und Sphingosin', ' oben Sphingosin, unten Ceramid'], 'B', 0, 'testbilder/040109.gif' ]) ;
  load_question(['Welche Fetts&auml;ure ist Vorl&auml;ufer der Eikosanoide?', ['Palmitins&auml;ure', ' '], ['Stearins&auml;ure', ' '], ['&Ouml;ls&auml;ure', ' '], ['Linolens&auml;ure', ' '], ['Arachidons&auml;ure', ' '], 'E', 0, 'none' ]) ;
  load_question(['Welches Lipid kann nicht verseift werden?', ['Phosphatidylethanolamin', ' enthält Phosphorsäureester'], ['Sphingosin', ' enthält keinen Ester'], ['Sphingomyelin', ' enthält Phosphorsäureester'], ['Cerebrosid', ' enthält verseifbare Amidbindung'], ['Phosphatidylcholin', ' enthält Phosphorsäureester'], 'B', 0, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber Cholesterin ist <span class="fett">falsch</span>?', ['Es ist ein Vorl&auml;ufer von Vitamin A und Prostaglandinen', ' Prostaglandine entstehen aus Arachidonsäure'], ['Es ist ein Vorl&auml;ufer von Gallens&auml;uren und Steroidhormonen', ' '], ['Es wird mit der Nahrung aufgenommen', ' '], ['Es kommt in Pflanzen nicht vor', ' '], ['Es ist Bestandteil von Membranen', ' '], 'A', 0, 'none' ]) ;
  load_question(['Welches ist <span class="fett">kein</span> Bestandteil von Gangliosiden?', ['Phosphat', ' Ganglioside enthalten FS, Glycerin oder Sphingosin und verschiedene Zucker und Zuckerderivate, aber kein Phosphat'], ['Sphingosin', ' Ganglioside enthalten FS, Glycerin oder Sphingosin und verschiedene Zucker und Zuckerderivate, aber kein Phosphat'], ['Fetts&auml;ure', ' Ganglioside enthalten FS, Glycerin oder Sphingosin und verschiedene Zucker und Zuckerderivate, aber kein Phosphat'], ['N-Acetylgalaktosamin', ' Ganglioside enthalten FS, Glycerin oder Sphingosin und verschiedene Zucker und Zuckerderivate, aber kein Phosphat'], ['N-Acetylglucosamin', ' Ganglioside enthalten FS, Glycerin oder Sphingosin und verschiedene Zucker und Zuckerderivate, aber kein Phosphat'], 'A', 0, 'none' ]) ;
  load_question(['Welche Fetts&auml;ure hat einen h&ouml;heren Schmelzpunkt als Palmitins&auml;ure (16:0)?', ['Myristins&auml;ure (14:0)', ' Der Schmelzpunkt nimmt mit der Kettenlänge zu und mit der Anzahl der Doppelbindungen ab.'], ['Palmitoleins&auml;ure (16:1)', ' Der Schmelzpunkt nimmt mit der Kettenlänge zu und mit der Anzahl der Doppelbindungen ab.'], ['Stearins&auml;ure (18:0)', ' Der Schmelzpunkt nimmt mit der Kettenlänge zu und mit der Anzahl der Doppelbindungen ab.'], ['Oleins&auml;ure (18:1)', ' Der Schmelzpunkt nimmt mit der Kettenlänge zu und mit der Anzahl der Doppelbindungen ab. '], ['&Ouml;ls&auml;ure (18:2)', ' Der Schmelzpunkt nimmt mit der Kettenlänge zu und mit der Anzahl der Doppelbindungen ab.'], 'C', 0, 'none' ]) ;
  load_question(['Welche Ladung tr&auml;gt Phosphatidylserin bei pH 7?', ['-2', ' Das Phosphat ist negativ geladen und das Serin trägt eine positive und eine negative Ladung'], ['-1', ' Das Phosphat ist negativ geladen und das Serin trägt eine positive und eine negative Ladung'], ['0', ' Das Phosphat ist negativ geladen und das Serin trägt eine positive und eine negative Ladung'], ['+1', ' Das Phosphat ist negativ geladen und das Serin trägt eine positive und eine negative Ladung'], ['+2', ' Das Phosphat ist negativ geladen und das Serin trägt eine positive und eine negative Ladung'], 'B', 0, 'none' ]) ;
  load_question(['Um welche Verbindung handelt es sich?', ['Steroidhormon', ' '], ['Vitamin A', ' '], ['Gallens&auml;ure', ' '], ['Sphingomyelin', ' '], ['Glykolipid', ' '], 'D', 0, 'testbilder/040101.gif' ]) ;
  load_question(['Um welche Verbindung handelt es sich?', ['Steroidhormon', ' '], ['Vitamin A', ' '], ['Gallens&auml;ure', ' '], ['Sphingomyelin', ' '], ['Glykolipid', ' '], 'E', 0, 'testbilder/040102.gif' ]) ;
  load_question(['Um welche Verbindung handelt es sich?', ['Steroidhormon', ' '], ['Vitamin A', ' '], ['Gallens&auml;ure', ' '], ['Sphingomyelin', ' '], ['Glykolipid', ' '], 'B', 0, 'testbilder/040104.gif' ]) ;
  load_question(['Um welche Verbindung handelt es sich?', ['Steroidhormon', ' '], ['Vitamin A', ' '], ['Gallens&auml;ure', ' '], ['Sphingomyelin', ' '], ['Glykolipid', ' '], 'A', 0, 'testbilder/040105.gif' ]) ;
  load_question(['Um welche Verbindung handelt es sich?', ['Steroidhormon', ' '], ['Vitamin A', ' '], ['Gallens&auml;ure', ' typisch für Gallensäure ist die saure Carboxylgruppe, sie macht das Molekül amphiphil'], ['Sphingomyelin', ' '], ['Glykolipid', ' '], 'C', 0, 'testbilder/040106.gif' ]) ;
  load_question(['Welche Eigenschaft ist den 4 Substanzen gemeinsam?', ['Es sind Alkohole', ' '], ['Sie kommen als Bestandteile von Glykolipiden vor', ' '], ['Sie kommen als Bestandteile von Phospholipiden vor', ' '], ['Sie kommen als Bestandteile von Terpenen vor', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'testbilder/040107.gif' ]) ;
  load_question(['Welche Fetts&auml;ure ist unges&auml;ttigt?', ['Palmitins&auml;ure', ' '], ['&Ouml;ls&auml;ure', ' '], ['Stearins&auml;ure', ' '], ['Arachidons&auml;ure', ' '], ['', ' '], ['0', '1', '0', '1'], 6, 'none' ]) ;
  load_question(['Welches Lipid ist eine amphiphile Substanz?', ['Cholesterin', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], ['Vitamin K', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], ['Prostaglandin', ' nur Gallensäure ist amphiphil; die Polarität der andern Moleküle ist zu gering, um sie amphiphil zu machen'], ['Gallens&auml;ure', ' '], ['', ' '], ['0', '0', '0', '1'], 6, 'none' ]) ;
  
}