// Fragen Editor 1.1

 
function get_questions() {

  load_question(['a) In einer <img src="testbilder/beta.gif">-Schleife kommt die Aminos&auml;ure Gly besonders selten vor<br><br>weil<br><br>b) Gly die Drehbarkeit der Peptidkette stark einschr&auml;nkt.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'E', 2, 'none' ]) ;
  load_question(['a) In nat&uuml;rlichen Proteinen kommen ausschliesslich L-Aminos&auml;uren vor<br><br>weil<br><br>b) D-Aminos&auml;uren keine Sekund&auml;rstrukturen ausbilden k&ouml;nnen.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' D-Aminosäuren können Sekundärstrukturen ausbilden, sie werden in der Natur aber nicht in Proteine eingebaut'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'C', 2, 'none' ]) ;
  load_question(['a) Van der Waals Bindungen zwischen den Seitenketten im Proteininnern stabilisieren die Terti&auml;rstruktur<br><br>weil<br><br>b) die polaren Seitenketten bevorzugt an der Oberfl&auml;che des Proteins liegen.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) In einem globul&auml;ren Protein kommen alle Aminos&auml;uren in a-Helices, ß-Faltbl&auml;ttern oder &beta-Schleifen vor<br><br>weil<br><br>b) diese Strukturen die Anzahl der H-Br&uuml;cken zwischen den Peptidbindungen optimieren.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', 'Nicht alle AS eines Proteins sind Bestandteil von Sekundärstrukturen.'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' nicht alle AS eines Proteins sind Bestandteil von Sekundärstrukturen'], ['a richtig, b falsch', 'Nicht alle AS eines Proteins sind Bestandteil von Sekundärstrukturen.'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Die Kontaktfl&auml;chen zwischen den Untereinheiten von H&auml;moglobin sind komplement&auml;r zueinander<br><br>weil<br><br>b) der hydrophobe Effekt den gr&ouml;ssten Energiebeitrag f&uuml;r den Zusammenhalt der Untereinheiten liefert.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'B', 2, 'none' ]) ;
  load_question(['a) Bei der Denaturierung bleiben die Sekund&auml;rstrukturelemente eines Proteins grossenteils erhalten<br><br>weil<br><br>b) diese durch sehr viele H-Bindungen stablisiert werden.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' Denaturierung lässt nur die Primärstruktur intakt'], ['a und b richtig; b als Begr&uuml;ndung von a falsch', 'Denaturierung lässt nur die Primärstruktur intakt.'], ['a richtig, b falsch', 'Denaturierung lässt nur die Primärstruktur intakt.'], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'D', 2, 'none' ]) ;
  load_question(['a) Als chemische Evolution bezeichnet man die Ver&auml;nderung der Aminos&auml;urensequenz verwandter Proteine aus verschiedenen Spezies<br><br>weil<br><br>b) die Sequenzunterschiede mit zunehmender evolution&auml;rer Distanz zunehmen.', ['a und b richtig; b als Begr&uuml;ndung von a richtig', ' '], ['a und b richtig; b als Begr&uuml;ndung von a falsch', ' '], ['a richtig, b falsch', ' '], ['a falsch, b richtig', ' '], ['a falsch, b falsch', ' '], 'A', 2, 'none' ]) ;
  load_question(['Das antiparallele ß-Faltblatt auf der Abbildung besteht aus 6 Str&auml;ngen, jeder Strang hat 7 Aminos&auml;uren. Hydrophobe Seitenketten sind gelb, hydrophile rot, das Peptidr&uuml;ckgrat gr&uuml;n und die ß-Schleifen grau. Welcher Sequenzausschnitt entspricht am ehesten dieser Struktur? y = eine hydrophobe Aminos&auml;ure, w = eine hydrophile Aminos&auml;ure, t = eine Aminos&auml;ure in einer ß-Schleife.', ['....y-y-y-y-w-w-w-t-t-t-t-y-y-y-y-w-w-w-t-t-t-t....', 'Reste, die in der Sequenz benachbart sind, schauen nach oben und nach unten; die Sequenz muss deshalb y-w-y-w... oder w-y-w-y... enthalten'], ['....y-w-y-w-y-w-y-t-t-t-t-y-w-y-w-y-w-y-t-t-t-t....', ' fast richtig, aber es sind je 3 hydrophobe und 4 hydrophile Reste pro Strang, daher muss die Sequenz w-y-w-y-w-y-w lauten; D ist korrekt'], [' ....y-y-w-w-y-y-w-t-t-t-t-y-y-w-w-y-y-w-t-t-t-t....', ' Reste, die in der Sequenz benachbart sind, schauen nach oben und nach unten; die Sequenz muss deshalb y-w-y-w... oder w-y-w-y... enthalten'], ['....w-y-w-y-w-y-w-t-t-t-t-w-y-w-y-w-y-w-t-t-t-t....', ' '], ['....w-w-w-w-w-w-w-t-t-t-t-y-y-y-y-y-y-y-t-t-t-t...', ' Reste, die in der Sequenz benachbart sind, schauen nach oben und nach unten; die Sequenz muss deshalb y-w-y-w... oder w-y-w-y... enthalten'], 'D', 0, 'testbilder/030201.jpg' ]) ;
  load_question(['Welcher Wert entspricht am ehesten der Fl&auml;che des in der Abbildung gr&uuml;n gezeichneten 6-str&auml;ngigen ß-Faltblatts mit je 7 Aminos&auml;uren pro Strang?', ['100 (Angstrom)<sup>2</sup>', ' Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['500 (Angstrom)<sup>2</sup>', ' Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['1000 (Angstrom)<sup>2</sup>', ' Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['2000 (Angstrom)<sup>2</sup>', 'Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], ['5000 (Angstrom)<sup>2</sup>', 'Der Abstand zwischen den AS beträgt 3.5 Angström und zwischen den Strängen etwa 4.7 Angström. Es sind 6 Stränge mit je 7 AS, die Fläche ist also etwa 5×4.7×6×3.5 = etwa 500 Angström^2'], 'B', 0, 'testbilder/030201.jpg' ]) ;
  load_question(['Welche Aussage &uuml;ber diese Struktur ist <span class="fett">falsch</span>?', ['Es ist ein antiparalleles Faltblatt.', ' '], ['Der Abstand zwischen den Peptidketten betr&auml;gt etwa 4.7 Angstrom.', ' '], ['Die Seitenketten liegen &uuml;ber und unter der Ebenen der Peptidbindungen.', ' '], ['Die Peptidbindungen liegen alle in derselben Ebene senkrecht zur Richtung der Peptidkette.', ' Die Ebenen der Peptidbindungen wechseln, daher der Name "Faltblatt" '], ['Es handelt sich um eine Struktur aus lauter L-Aminos&auml;uren.', ' '], 'D', 0, 'testbilder/030202.gif' ]) ;
  load_question(['Welche Aussage &uuml;ber Proteindom&auml;nen ist <span class="fett">falsch</span>?', ['Sie enthalten oft 10-20 Aminos&auml;uren.', ' Domänen sind grösser, typisch sind 100-150 Aminosäuren'], ['Sie sind oft strukturell unabh&auml;ngig.', ' '], ['Sie haben oft eine spezialisierte Funktion.', ' '], ['Sie &auml;hneln oft einem kleinen globul&auml;ren Protein.', ' '], ['Sie werden oft auf der DNA durch ein einzelnes Exon kodiert.', ' '], 'A', 0, 'none' ]) ;
  load_question(['Wieviele H-Bindung mit anderen Aminos&auml;uren macht die 10. Aminos&auml;ure in einer a-Helix aus 12 Aminos&auml;uren?', ['0', ' Die 10. AS kann noch eine H-Bindung machen, denn diese liegen zwischen AS i und i+4'], ['1', ' Die H-Bindungen liegen zwischen der AS i und i+4, daher kann die 10. AS nur noch eine H-Bindung machen'], ['2', ' Die H-Bindungen liegen zwischen der AS i und i+4, daher kann die 10. AS nur noch eine H-Bindung machen'], ['3', ' Eine AS in einer alpha-Helix kann höchstens zwei H-Bindung machen'], ['4', ' Eine AS in einer alpha-Helix kann höchstens zwei H-Bindung machen'], 'B', 0, 'none' ]) ;
  load_question(['Welche Aminos&auml;ure einer a-Helix macht eine H-Br&uuml;cke mit der 2. Aminos&auml;ure?', ['1. Aminos&auml;ure', ' die H-Bindung liegen zwischen AS i und i+4 '], ['3. Aminos&auml;ure', 'Die H-Bindung liegen zwischen AS i und i+4.'], ['4. Aminos&auml;ure', 'Die H-Bindung liegen zwischen AS i und i+4.'], ['5. Aminos&auml;ure', 'Die H-Bindung liegen zwischen AS i und i+4.'], ['6. Aminos&auml;ure', 'Die H-Bindung liegen zwischen AS i und i+4.'], 'E', 0, 'none' ]) ;
  load_question(['Wieviele verschiedene Disulfidbr&uuml;cken k&ouml;nnen in einer Polypeptidkette mit 6 Cysteinresten entstehen?', ['6', ' 5 x 3 x 1 Möglichkeiten'], ['12', ' 5 x 3 x 1 Möglichkeiten'], ['15', ' 5 x 3 x 1 Möglichkeiten'], ['21', ' 5 x 3 x 1 Möglichkeiten'], ['36', '5 x 3 x 1 Möglichkeiten '], 'C', 0, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber Konformations&auml;nderungen ist <span class="fett">falsch</span>?', ['Konformation&auml;nderungen werden durch die Bindung von Substraten an Enzyme ausgel&ouml;st', ' '], ['Konformations&auml;nderungen sind charakterisiert durch die Spaltung und Neubildung von nicht-kovalenten Bindungen', ' '], ['Konformations&auml;nderungen sind reversibel', ' '], ['Der Energiegehalt der verschiedenen Konformationen eines Proteins ist &auml;hnlich', ' '], ['Bei Konformations&auml;nderungen &auml;ndert die Sekund&auml;rstruktur nicht', 'Nur die Primärstruktur ändert bei einer Konformationsänderung nicht'], 'E', 0, 'none' ]) ;
  load_question(['Unter welchen Bedingungen wird ein Protein in der Regel NICHT denaturiert?', ['pH 1', ' '], ['8 M Harnstoff', ' '], ['6 M Guanidiniumhydrochlorid ', ' '], ['2 M Kochsalz', ' Kochsalz kann zwar die Konformation eines Proteins beeinflussen, aber es wird in der Regel durch Salz nicht denaturiert'], ['100 °C', ' '], 'D', 0, 'none' ]) ;
  load_question(['Die gezeigte Helix aus 13 Resten hat eine polare (violett) und eine apolare (grau) Seite. Welche Sequenz entspricht am ehesten dieser Helix? w = polare Aminos&auml;ure, y = apolare Aminos&auml;ure.', ['w-w-w-w-w-w-w-y-y-y-y-y-y', ' 3.6 AS pro Umdrehung: Es können also höchstens 1-2 AS auf der gleichen Seite der Helix liegen'], ['w-w-y-y-w-w-y-y-w-w-y-y-w', ' 3.6 AS pro Umdrehung: Es können also nicht immer zwei AS auf der gleichen Seite der Helix liegen'], ['w-w-w-y-y-y-w-w-w-y-y-y-w', ' 3.6 AS pro Umdrehung: Es können also höchstens 1-2 AS auf der gleichen Seite der Helix liegen'], ['w-y-w-y-w-y-w-y-w-y-w-y-w', ' 3.6 AS pro Umdrehung: Nicht jede zweite AS kann auf der gleichen Seite der Helix liegen'], ['y-w-w-y-y-w-w-y-w-w-y-y-w', ' '], 'E', 0, 'testbilder/030203.jpg' ]) ;
  load_question(['Welches Merkmal der Quart&auml;rstruktur ist falsch? ', ['Die Kontaktfl&auml;chen zwischen den Untereinheiten zeigen eine r&auml;umlich komplement&auml;re Struktur', ' '], ['Hydrophobe Wechselwirkungen stabilisieren den Zusammenhalt der Untereinheiten', ' '], ['H-Bindungen stabilisieren den Zusammenhalt der Untereinheiten', ' '], ['Die Quart&auml;rstrukturen entsteht spontan durch Selbstorganisation', ' '], ['Zur Bildung der Quart&auml;struktur braucht es Untereinheiten mit verschiedenen Sequenzen', ' '], 'E', 0, 'none' ]) ;
  load_question(['Welche Beobachtung zeigt, dass die Information f&uuml;r die native Proteinstruktur in der Aminos&auml;urensequenz enthalten ist?', ['Verdauung des nativen Proteins mit einer Protease zerst&ouml;rt seine biologische Aktivit&auml;t ', ' '], ['Kochen des Proteins zerst&ouml;rt seine biologische Aktivit&auml;t', ' '], ['Dialyse des nativen Proteins gegen Puffer von pH 7 zerst&ouml;rt seine biologische Aktivit&auml;t', ' '], ['Dialyse des denaturierten Proteins gegen Puffer von pH 7 bringt seine biologische Aktivit&auml;t zur&uuml;ck', ' '], ['Dialyse des denaturierten Proteins gegen 8 M Harnstoffl&ouml;sung bringt seine biologische Aktivit&auml;t zur&uuml;ck', ' '], 'D', 0, 'none' ]) ;
  load_question(['Was erkl&auml;rt die Verklumpung von H&auml;moglobin S (Sichelzellan&auml;mie), die man bei H&auml;moglobin A (normales H&auml;moglobin des Erwachsenen) nicht beobachtet? ', ['HbS enth&auml;lt mehr hydrophobe Aminos&auml;uren als HbA', ' '], ['HbS enth&auml;lt mehr hydrophile Aminos&auml;uren als HbA', ' '], ['In einer einzigen Position enth&auml;lt HbS ein Glu anstelle eines Val', ' '], ['In einer einzigen Position enth&auml;lt HbS ein Val anstelle eines Glu', ' '], ['HbS bindet Sauerstoff schlechter als HbA', ' '], 'D', 0, 'none' ]) ;
  load_question(['Welche Eigenschaft einer Polypeptidkette ist f&uuml;r die Ausbildung von Sekund&auml;rstruktur hauptverantwortlich?', ['Freie Drehbarkeit der Peptidbindung', ' '], ['H-Br&uuml;cken zwischen Seitenketten', ' '], ['Beweglichkeit der Seitenketten', ' '], ['H-Br&uuml;cken zwischen Peptidbindungen', ' '], ['', ' '], ['0', '0', '0', '1'], 6, 'none' ]) ;
  load_question(['Welche Eigenschaft einer Polypeptidkette ist f&uuml;r die Ausbildung von Sekund&auml;rstruktur hauptverantwortlich?', ['Freie Drehbarkeit der Peptidbindung', ' '], ['H-Br&uuml;cken zwischen Seitenketten', ' '], ['Beweglichkeit der Seitenketten', ' '], ['H-Br&uuml;cken zwischen Peptidbindungen', ' '], ['', ' '], ['0', '0', '0', '1'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber Disulfidbr&uuml;cken ist richtig?', ['Sie k&ouml;nnen Peptidketten miteinander verkn&uuml;pfen', ' '], ['Sie stabilisieren vor allem intrazellul&auml;re Proteine', ' '], ['Sie k&ouml;nnen innerhalb einer Peptidkette liegen', ' '], ['Sie werden durch Oxidationsmittel gespalten.', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber die a-Helix ist richtig?', ['Zwei H-Bindungen pro Peptidbindung', ' '], ['Seitenketten gegen aussen gerichtet', ' '], ['Ebenen der Peptidbindung parallel zur Helixachse', ' '], ['H-Bindung zwischen Aminos&auml;uren i und i+4.', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber das <img src="testbilder/beta.gif">-Faltblatt ist richtig?', ['zwei H-Bindungen pro Peptidbindung', ' '], ['Seitenketten abwechselnd nach oben und unten gerichtet', ' '], ['H-Bindungen senkrecht zur Richtung der Peptidketten', ' '], ['H-Bindung zwischen Aminos&auml;uren i und i+3.', ' '], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber die prosthetische H&auml;mgruppe von Myoglobin ist <span class="fett">falsch</span>?', ['Sie ist kovalent mit der Peptidkette verkn&uuml;pft.', ' '], ['Sie liegt an der Oberfl&auml;che des Molek&uuml;ls.', ' '], ['Sie ist vorwiegend von polaren Aminos&auml;ureseitenketten umgeben.', ' '], ['Sie enth&auml;lt im Zentrum ein Eisen.', ' '], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aminos&auml;ureseitenketten k&ouml;nnen im Proteininnern nur &uuml;ber van der Waals-Bindungen miteinander interagieren?', ['Val-Ser', ' '], ['Val-Leu', ' '], ['Ile-Thr', ' '], ['Gln-Ser', ' auch im Innern kann sich eine H-Bindung zwischen den Seitenketten von Gln und Ser ausbilden '], ['', ' '], ['1', '1', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber Denaturierung ist <span class="fett">falsch</span>?', ['Denaturierung ist immer reversibel', ' '], ['Denaturierung zerst&ouml;rt die Prim&auml;rstruktur nie', ' '], ['Bei der Denaturierung f&auml;llt das Protein immer aus', ' '], ['Denaturierung zerst&ouml;rt stets die biologische Aktivit&auml;t des Proteins', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'none' ]) ;
  load_question(['Welche Aussage &uuml;ber das gezeigte Protein ist richtig?', ['Es enth&auml;lt alpha-Helix und beta-Faltblatt', ' '], ['Es enth&auml;lt keine beta-Schleifen', ' '], ['Es ist aus verschiedenen Dom&auml;nen aufgebaut', ' '], ['Es ist etwa 50 Aminos&auml;uren lang.', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'testbilder/domainstructure.gif' ]) ;
  load_question(['Welche Aussage &uuml;ber die Flexibilit&auml;t von Proteinen ist richtig?', ['sie erm&ouml;glicht unterschiedliche Konformationen eines Proteins', ' '], ['sie ist daf&uuml;r verantwortlich, dass die meisten Proteine zwischen 50 und 100 °C denaturieren ', ' '], ['sie tr&auml;gt zur Spezifit&auml;t der Enzyme bei', ' '], ['sie ist in der Kristallstruktur eines Proteins nicht sichtbar', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'none' ]) ;
  load_question(['Unter welchen Bedingungen wird ein Protein denaturiert?', ['kochen bei pH 7', ' '], ['kochen bei pH 3', ' '], ['mit einer konzentrierten L&ouml;sung des Molek&uuml;ls A behandeln ', ' '], ['mit einer konzentrierten L&ouml;sung des Molek&uuml;ls B behandeln ', ' '], ['', ' '], ['1', '1', '1', '1'], 6, 'testbilder/urea+gdmcl.gif' ]) ;
  load_question(['Weshalb sind die Strukturen von Myoglobin (blau) und der alpha-Untereinheit von H&auml;moglobin (gelb) sehr &auml;hnlich? ', ['weil die beiden Proteine &auml;hnliche Sequenzen haben ', ' '], ['weil die beiden Proteine unter identischen Bedingungen kristallisiert worden sind ', ' '], ['weil die beiden Proteine in der Evolution aus einem gemeinsamen Vorl&auml;uferprotein entstanden sind ', ' '], ['weil die prosthetische H&auml;mgruppe &auml;hnliche Strukturen erzeugt. ', ' '], ['', ' '], ['1', '0', '1', '0'], 6, 'testbilder/Hb+Mb.gif' ]) ;
  load_question(['Welche Zuordnungen sind richtig?<br><br>A Lineare Abfolge der Aminos&auml;uren<br>B R&auml;umliche Gesamtstruktur einer Polypeptidkette<br>C Abschnitte mit regelm&auml;ssiger Faltung<br>D Assoziation von mehreren Polypeptidketten<br>E Kovalente Verkn&uuml;pfung von Polypeptidketten &uuml;ber Aminos&auml;ureseitenketten', ['Disulfidbr&uuml;cke', ' '], ['Prim&auml;rstruktur', ' '], ['Sekund&auml;rstruktur', ' '], ['Terti&auml;rstruktur', ' '], ['Quart&auml;rstruktur', ' '], ['E', 'A', 'C', 'B', 'D'], 3, 'none' ]) ;
  load_question(['Welche Aussage zu dieser Struktur trifft zu?', ['sie enth&auml;lt ein antiparalleles Faltblatt', ' '], ['Str&auml;nge des Faltblatts sind mit einer alpha-Helix verkn&uuml;pft ', ' '], ['Str&auml;nge des Faltblatts sind mit beta-Schleifen verbunden', ' '], ['in der Prim&auml;rstruktur liegt die alpha-Helix direkt vor dem C-Term', ' '], ['', ' '], ['1', '1', '1', '0'], 6, 'testbilder/sheet5.gif' ]) ;
  load_question(['Welche Zuordnung passt am besten?<br><br>A hydrophober Effekt<br>B Kontaktfl&auml;che zwischen den Untereinheiten eines oligomeren Proteins<br>C ionische Bindung<br>D Proteindom&auml;ne<br>E <img src="testbilder/alpha.gif">-Helix', ['r&auml;umliche Komplementarit&auml;t', ' '], ['Seitenketten von Asp und Arg', ' '], ['Tendenz von Aminos&auml;uren, den Kontakt mit Wasser zu meiden', ' '], ['Myoglobin', ' '], ['Exon auf der DNA', ' '], ['B', 'C', 'A', 'E', 'D'], 3, 'none' ]) ;
  load_question(['Welche Zuordnung ist richtig?<br><br>A <img src="testbilder/beta.gif">-Faltblatt<br>B Coiled Coil<br>C <img src="testbilder/beta.gif">-Schleife<br>D Kollagenhelix<br>E Keratin', ['Faserprotein mit einer Tripelhelix als Grundstruktur', ' '], ['Faserprotein mit vielen Disulfidbr&uuml;cken', ' '], ['zwei umeinander gewundene <img src="testbilder/alpha.gif">-Helices', ' '], ['H-Br&uuml;cke zwischen der 1. und der 4. Aminos&auml;ure', ' '], ['regelm&auml;ssige Struktur mit H-Br&uuml;cken zwischen fast gestreckten Peptidketten', ' '], ['D', 'E', 'B', 'C', 'A'], 3, 'none' ]) ;
  load_question(['Welche Zuordnung ist richtig?<br><br>A Chaperone<br>B Proteasom<br>C Denaturierung<br>D Reduktion von Disulfidbr&uuml;cken<br>E endoplasmatisches Retikulum', ['HO-CH<sub>3</sub>-CH<sub>2</sub>-SH', ' '], ['NH<sub>2</sub>-CO-NH<sub>2</sub>', ' '], ['Proteolyse', ' '], ['Proteinaggregate', ' '], ['Proteinsynthese', ' '], ['D', 'C', 'B', 'A', 'E'], 3, 'none' ]) ;
  load_question(['Welche Zuordung trifft zu?<br><br>A Sichelzellan&auml;mie<br>B Chaperone<br>C Serinproteasen<br>D Histone<br>E Plasmodium falciparum', ['Proteinfaltung', ' '], ['Bindung an DNA', ' '], ['basiche Proteine', ' '], ['molekulare Krankheit', ' '], ['Malaria', ' '], ['B', 'D', 'D', 'A', 'E'], 3, 'none' ]) ;
  load_question(['Welche Arten von Bindungen und Wechselwirkungen sind mit den Buchstaben A bis E gekennzeichnet??', ['hydrophobe Wechselwirkungen', ' '], ['elektrostatische Anziehung', ' '], ['Disulfidbr&uuml;cke', ' '], ['kovalente Bindung', ' '], ['H-Bindungen', ' '], ['B', 'E', 'A', 'C', 'D'], 3, 'testbilder/SK-Wechselwirk.gif' ]) ;
  
}
